### ISSUE TITLE
[01] 왜 Next.js를 사용했나요? 리액트와 어떤 차이점이 있나요?

### ISSUE THREAD

**Issue by hyeyoonS** [QueenCards/ProjectAnalysis#1]
## React와 Next.js에 대한 간단한 설명과 Next.js를 사용한 이유

리액트는 자바스크립트 기반의 SPA 라이브러리입니다. 컴포넌트를 활용하여 UI를 쉽고 효율적으로 만들 수 있습니다. 
Next.js는 SSR으로 동작하는 리액트의 프레임워크로, 리액트의 단점을 보완하는 여러 기능을 제공합니다. 또한 비슷한 종류의 프레임워크에서 가장 높은 시장 점유율을 보입니다. 처음 웹개발을 시작하는 입장에서, 만족도가 높고 활발한 커뮤니티를 가진 Next.js가 가장 유용할 것이라 판단하였습니다. 

![npmtrend](https://github.com/QueenCards/ProjectAnalysis/assets/144667455/884c058c-8b8f-43ec-8235-c35d80346e7e)

 

## React와 Next.js의 차이점

가장 큰 차이점은 **React와 Next.JS의 동작 방식**입니다. 리액트는 클라이언트에서 동작하는 라이브러리로, 초기 렌더링 시 HTML을 생성하지 않고 JavaScript를 사용하여 DOM을 조작하는 방식으로 동작합니다.

웹사이트를 요청을 할 때, 현재 사용하지 않지만 필요한 모든 컴포넌트를 다운로드 하고, 빈 HTML을 가져와 이후 Script를 로딩하는 방시. 따라서 모든 자바스크립트가 로드된 후 사용자에게 보여지므로, 초기의 로딩 시간의 지연이 발생할 수 있습니다. 또한 검색엔진은 HTML을 기반으로 동작하는 것인데, 빈 HTML을 가져오므로 SEO(검색엔진최적화)에 취약합니다. 크롤링 봇(HTML만을 크롤링하기에)이 meta태그를 가져갈 수 없기 때문입니다.

Next.js는 SSR을 기반으로 프리렌더링을 지원합니다. 초기에 보여지는 화면을 빌드 단계에서 데이터를 받아 정적으로 생성하거나, 또는 SSR(Server Side Rendering)을 할 수 있습니다. 이를 통해 사용자에게 보여지는 첫 페이지가 서버에서 이미 렌더링 된 후에 전송되기 때문에 초기 로딩 시간을 단축할 수 있고, 렌더링 된 HTML을 가져오므로 SEO(검색엔진최적화)에 강점이 있습니다.

이와 관련하여, Next.js는 자동 코드 스플리팅 또한 지원합니다. 자동 코드 스플리팅을 통해 초기 로드 시 필요한 최소한의 코드(서버 사이드 컴포넌트)만 다운로드하여 실행하므로, 앱의 초기 로딩 속도를 추가로 개선할 수 있습니다. 

> 💡 자동 코드 스플리팅에 대하여!! 
서버 컴포넌트와 클라이언트 컴포넌트를 자동으로 나눠서 해석한다는 의미입니다.
서버 컴포넌트는 서버에서 먼저 해석된 이후 클라이언트로 전달되어 곧바로 브라우저에 보여지는 반면, 클라이언트 컴포넌트는 클라이언트가 JS번들을 다운받은 후 (hydration) 해석을 하므로 나중에 보여집니다.
> 

### Single File Components
또한 Next.js는 Single File Components로 해당 컴포넌트만 스코프를 가지는 CSS를 **style.jsx** 를 통하여 만들 수 있습니다.
각 컴포넌트의 CSS는 해당 컴포넌트의 스코프 내에서만 적용되므로, CSS클래스명의 충돌을 방지하고 의도하지 않게 스타일이 중복되거나 덮어 씌워지는 현상을 방지할 수 있습니다.
또 컴포넌트와 스타일을 함께 관리하므로 유지보수성이 우수하고 가독성을 향상시킬 수 있습니다.

### 라우팅 시스템

리액트에서 라우팅을 하려면 일반적으로 React Router라는 라이브러리를 사용해야 했습니다. 최상위 컴포넌트에서 `<BrowserRouter>`를 import하여 라우터를 구성하고, `<Route>`와 ‘path’를 별도로 설정해주어야 했습니다. 
Next.js는 페이지 경로를 파일/폴더 구조를 통해 자동으로 설정할 수 있습니다. 별도의 라우팅 설정 없이 편리하게 페이지를 추가할 수 있고, 프로젝트 구조가 명확하게 보여집니다.

### next/Image
Image 컴포넌트를 통해 이미지 크기를 자동으로 최적화합니다. 또한 이미지를 곧바로 로드하지 않고, lazy-loading을 통해 뷰포트에 이미지가 필요한 순간에 이미지를 가져와 최적화 합니다.

### next/Font
빌드 타임에 폰트를 다운받아 미리 정적 파일로 만들어 놓습니다. 따라서 유저가 어플리케이션을 실행할 때 별도의 요청이 필요하지 않아 유저 경험을 향상시킬 수 있습니다.

### next/Link
클라이언트 측 라우팅을 사용하여 페이지 간의 부드러운 전환을 구현할 수 있습니다.
이때 페이지는 서버에서 미리 렌더링 되고, 사용자가 이동을 할 때 새로운 페이지를 서버로 요청하지 않고 클라이언트에서만 렌더링 되도록 합니다. 이로 인해 사용자 경험이 향상되고 페이지 간의 전환 속도가 빨라집니다.
또한 next/link는 HTML의 <a> 요소를 렌더링하기 때문에 검색 엔진 최적화(SEO)에도 도움이 됩니다.

### API-Routes
API-Routes를 통해 직접 BFF(백엔드 for 프론트엔드) 구현을 할 수 있습니다.

### 왜 Next.js ? 
- React만을 사용했을 때보다 Next.js를 사용했을 때 확장되어 제공되는 기능들이 많음
- 높은 시장 점유율과 활발한 커뮤니티

### 리액트와의 차이점?
- API routes로 서버리스 함수 구현이 가능
- 파일시스템 기반 라우팅으로 리액트에 비해 간편한 라우팅
- 프리렌더링(SSG, SSR) 과 코드스플리팅 자동 지원으로 초기 로딩 속도 향상
- next/image, next/link 등 최적화 방법 제공
- 서버에서 렌더링 된 html을 받아오므로 검색 엔진 최적화에 유리

**Comment by Nahyun-Kang** [comment]
React는 자바스크립트 기반 웹 프레임워크/라이브러리이고, Next.js는 리액트 친화적인 자바스크립트 오픈소스 웹 프레임워크로, 서버 사이드 렌더링(Server-side Rendering), 정적 사이트 생성(Static site generation(SSG) 등 프리 렌더링 기능을 추가적으로 제공합니다. Next.js가 제공하는 다양한 렌더링 방식으로, React의 렌더링 방식인 CSR이 지닌 검색 엔진 최적화 어려움, 초기 실행 시 성능 부담 문제와 레이아웃이 순간적으로 움직이는 문제 등 해결할 수 있습니다.

**Comment by Jyophie** [comment]
React만 사용하는 것에 비해 Next.js를 사용했을때 확장되어 제공되는 기능들이 있습니다.

1. CSR과 SSR의 차이
React는 CSR(클라이언트 사이드 렌더링) 기반으로 작동되고, Next.js는 SSR(서버 사이드 렌더링)으로 서버에서 미리 페이지를 렌더링해주는 특징이 있습니다. Next.js가 미리 페이지를 렌더링해서 보여주기 때문에 초기 로딩 속도가 빠르고, 검색 엔진 최적화(SEO)에 더 큰 이점을 지니고 있습니다.

2. SSG(정적 사이트 생성)
Next.js는 빌드 타임에 페이지를 생성하여 정적 파일로 제공할 수 있어 서버 부하를 줄이고 페이지 로드 시간을 더 단축시킬 수 있습니다.

3. 파일 기반 라우팅
Next.js는 페이지 경로를 파일/폴더 구조를 통해 자동으로 설정할 수 있습니다. 별도의 라우팅 설정 없이 편리하게 페이지를 추가할 수 있고, 프로젝트 구조가 명확하게 보여집니다.

**Comment by olseul** [comment]
Next.js는 서버 사이드 렌더링을 기본적으로 지원합니다. 사용자에게 보여지는 첫 페이지가 서버에서 렌더링되어 전송되기 때문에 초기 로딩 시간이 단축된다는 장점이 있는 반면, 리액트는 클라이언트 사이드 렌더링을 사용합니다. 이는 모든 자바스크립트가 로드되고 난 후에야 사용자에게 보여지기 시작합니다. 그래서 초기 로딩 시간이 오래 걸릴 수 있습니다. 

또한, Next.js는 빌드 타임에 HTML 파일들을 생성합니다. 이렇게 사전에 생성된 페이지는 로딩 시간 없이 바로 제공될 수 있지만 리액트 자체는 SSG를 지원하지 않습니다.

**Comment by wise-Ag** [comment]
Next.js는 리액트기반의 프레임워크로 추가적인 기능을 사용할 수 있습니다.

React는 클라이언트 사이드 렌더링을, Next.js는 서버 사이드 렌더링을 제공합니다.
CSR이란 사용자의 브라우저에서 요청한 html파일을 렌더링 하여 보여주는 방식으로
초기 렌더링 속도가 느리고 검색엔진최적화에 불리한 점이 있습니다.
SSR이란 서버에서 렌더링한 html을 보내주는 방식으로 속도가 빠르고 검색엔진최적화에 유리합니다.
Next.js는 SSR뿐만 아니라 CSR도 사용이 가능하여 유연하게 사용할 수 있습니다.

Next.js는 페이지 기반의 라우팅을 하기 때문에 별도의 경로로 라우팅을 해줄 필요가 없어 간단합니다.

next/image, next/link, next/font등의 최적화 이점이 있습니다.
next/font : 빌드 타임에 폰트를 다운받아 미리 정적 파일로 호스팅해놓습니다. 유저가 어플리케이션을 실행할 때 별도의 요청이 필요하지 않습니다.
next/image :
뷰포트 크기별로 이미지 사이즈를 조정합니다.
이미지를 로딩할때 레이아웃이 이동하는 layout shift를 예방합니다.
이미지가 뷰포트에 들어올 때 이미지를 로드합니다. 이미지를 미리 로드하지 않음으로써 빠른 속도를 제공합니다.
next/link : prefetch를 제공합니다.

**Comment by HaydenDevK** [comment]
Next.js는 React.js를 기반으로 기능을 확장하여 다양한 부가 기능을 제공하는 프레임워크로, 가장 결정적인 차이는 SSR를 쉽게 구현할 수 있다는 점입니다. 
<프로젝트이름>은 실시간 업데이트가 활발하게 일어나는 서비스로, SSR을 통해 유저에게 최적의 성능과 사용자 경험을 제공하고 SEO 이점을 취하기 위해 Next.js를 채택하였습니다.

**Comment by Eugene-A-01** [comment]
Next.js를 사용한 가장 큰 이유는 서버사이드 렌더링과 SEO에서 이점을 가져갈 수 있기 때문입니다. 기본적으로 리액트는 클라이언트 사이드 렌더링을 하기 때문에, 첫 로딩이 길거나 SEO에 약하다는 점이 있었습니다. 

제 프로젝트에서는 Next.js를 app routing 방법으로 이용함으로써 기본적으로 서버사이드 렌더링을 하도록 하였고, 이로써 SEO와 초기로딩 속도 향상, 프리리로딩 등의 장점을 가져갔습니다.
 
Next.js를 사용한 큰 이유는 SSR 이지만, 프로젝트를 하면서 느낀 리액트에 비해 가진 장점 몇가지가 더 있었습니다. 대표적으로 API-Routes를 통해 직접 BFF(백엔드 for 프론트엔드) 구현을 할 수 있었고, 이미지 최적화나 next.js의 Link 태그로 인한 페이지 리로드 없이 페이지 이동을 할 수 있었습니다.

**Comment by kanglocal** [comment]
Next는 리액트 기반의 서버사이드 렌더링 프레임워크이다.
개발에서 매우 중요한 성능 및 사용성 개선 기능을 제공한다.

React는 유저 인터페이스를 구축하기 위한 JavaScript 라이브러리이다.
(JavaScript기반의 SPA웹 프레임워크 이다.)

### 차이점
1. React는 클라이언트 측에서만 렌더링되지만, Next는 서버사이드 렌더링 가능하다.

2. Next.js는 빌드 시점에 페이지를 렌더링하고 HTML파일을 생성하여 정적 사이트를 생성할 수 있다.

3. Next.js는 파일 시스템 기반 라우팅을 사용한다. 따라서 개발자가 페이지 및 경로를 생성하고 구성하는 데 편리하다.

#### +) 리액트의 단점은?
1. 클라이언트에서 페이지를 만들기때문에 페이지간 전환이 부드러워지는 장점이 있으나, HTML, JS를 다운받는동안 렌더링이 불가능하기에 첫 페이지의 로딩 속도가 느리다.
2. CSR의 특성상 HTML, JS를 보낸 뒤 클라이언트의 브라우저에서 JS를 실행시켜 화면을 그리기때문에 크롤링 봇(HTML만을 크롤링하기에)이 meta태그를 가져갈 수 없다. SEO에 취약하다.
