### ISSUE TITLE
[14] ReactQuery를 왜 썼나요? 이점이 뭔가요? next.js를 채택했다면 사용하지 않을 수도 있지 않나요? 

### ISSUE THREAD

**Issue by hyeyoonS** [QueenCards/ProjectAnalysis#16]
## 📎 질문
 ReactQuery를 왜 썼나요? 이점이 뭔가요? next.js를 채택했다면 사용하지 않을 수도 있지 않나요? 

## ✏ 구술 답변 키워드
*  reactQuery의 정의
  * 서버상태와의 동기화, 캐싱, 업데이트 및 패칭을 쉽게 도와주는 라이브러리.
* 사용한 이유
  * 클라이언트 데이터/서버데이터의 분리
  * 캐싱으로 서버 부하 감소
* 이점
  * 데이터 패칭, 캐싱, 동기화
  * devtools 지원
  * 무한스크롤 간편하게 구현
  * garbage collection
* 사용하지 않았을때의 큰 단점
  * 캐싱 불편 - 서버 부하 증가 또는 에러발생으로 이어질 수 있음.
  * 서버데이터와의 동기화 로직 추가 작성 필요 - 데이터가 변경됐는지 확인을 위한 로직이 추가로 필요
  * 요청 실패로인한 재시도 로직 추가 작성 필요 - 요청 실패시 재시도하는 로직이 추가로 필요
  * 서버데이터와 클라이언트 데이터의 혼합 - useState, useEffect등에서 서버데이터, 클라이언트데이터가 혼합되어 가독성이 나빠지며 잠재적 에러 발생 확률 증가.
* 대체 라이브러리 : SWR
  * 동기식 API를 제공하는 react hooks 라이브러리.
  * react hooks용으로 설계되어있음.
  * 단일 API 엔드포인트에서 데이터를 가져오는 것으로 국한된다.
  * 에러 처리 방법 미제공 등의 단점으로 reactQuery 사용.

### reactQuery란
* 애플리케이션에서 서버 상태와 동기화 및 업데이트, 캐싱, 패칭을 쉽게 할 수 있도록 도와주는 라이브러리.
* 기존의 상태관리 라이브러리는 클라이언트 상태의 작업에는 적합하지만 비동기 또는 서버 상태의 작업에는 그다지 적합하지 않다.
### reactQuery 사용 이유
* 가장 큰 이유는 클라이언트 데이터와 서버 데이터의 분리 및 캐싱기능이다.
### reactQeury의 이점
* 서버상태를 불러오고, 캐싱하고, 지속적으로 동기화하고, 업데이트한다.
* React Component내부에서 간단하고 직관적으로 API를 사용할 수 있다.
* 캐싱, window focus refetching등 다양한 기능이 있어 API요청과 관련된 번잡한 작업 없이 핵심로직에 집중할 수 있다.
  * 캐싱 : 특정 데이터의 복사본을 (캐시라 불리는 임시 저장소에) 저장하여 이후 동일한 데이터에 재접근하는 속도를 높일 수 있다. 반복적인 비동기 데이터 호출을 방지하면 불필요한 API호출을 줄여 서버 부하를 줄일 수 있다.
  * window focus refetching : 사용자가 애플리케이션을 떠났다고 돌아왔을 때, 쿼리 데이터가 오래된경우 자동으로 백그라운드에서 새로운 데이터를 요청한다. (옵션을 통해 활성화/비활성화 가능)
* devtools를 지원해 개발모드에서 데이터의 흐름을 파악할 수 있다.
* 페이지 관련 기능이 존재하기때문에 무한스크롤 기능 구현이 쉽다.
* 지정된 시간동안 쿼리가 사용되지 않는다면 자동으로 메모리를 해제하는 Auto Garbage Collection 기능이 있다.
* tanstack/react-query로 변경되며 React에 국한되지 않은 범용 프론트엔드로 개선되었다.
### reactQuery를 사용하지 않았을 때에는?
* 캐싱불가
  * 한 API에대한 요청시 따로 저장하는 로직이 없다면 계속해서 서버의 응답을 받아야한다.
* 서버데이터와의 동기화 불가
  * 데이터가 변경된경우, 새 데이터를 받아온 후 다시 렌더링하지 않으면 새로운 데이터를 볼 수 없다.
* 요청 실패로 인한 재시도
  * 잠깐 인터넷이 끊겼거나 서버가 내려간 경우, 따로 재시도에 대한 로직을 작성해주지않으면 그대로 에러를 반환하게된다. (reqctQuery는 retry옵션으로 재시도할 수 있다.)
* 서버데이터와 클라이언트 데이터의 혼합
  * isLoading, isError 와 같은 state 와 서버에서 받은 데이터의 state등이 혼합된다.
  
<details>
<summary>
추가 ) reactQuery의 사용방법([react-query 개념 및 정리](https://kyounghwan01.github.io/blog/React/react-query/basic/#usequeries))
</summary>

* useQuery : get API
  * unique key, api호출함수를 인자로 가짐.
```tsx
const Todos = () => {
  const { isLoading, isError, data, error } = useQuery("todos", fetchTodoList, {
    refetchOnWindowFocus: false, 
    retry: 0, 
    onSuccess: data => {
      // 성공시 호출
      console.log(data);
    },
    onError: e => {
      // 실패시 호출 (401, 404 같은 error가 아니라 정말 api 호출이 실패한 경우만 호출.)
      console.log(e.message);
    }
  });

      // isLoading, isError를 따로 받지 않고, status 하나만 받아도 처리 가능
	  // ex) if(status === "loading")
  if (isLoading) {
    return <span>Loading...</span>;
  }

  if (isError) {
    return <span>Error: {error.message}</span>;
  }

  return (
    <ul>
      {data.map(todo => (
        <li key={todo.id}>{todo.title}</li>
      ))}
    </ul>
  );
};
```

* useQuery 동기적 실행 : enabled 옵션으로
```tsx
const { data: todoList, error, isFetching } = useQuery("todos", fetchTodoList);
const { data: nextTodo, error, isFetching } = useQuery(
  "nextTodos",
  fetchNextTodoList,
  {
    enabled: !!todoList // true가 되면 fetchNextTodoList를 실행한다
  }
);
```
* useQueries : 여러 비동기 호출을 하는 경우
```tsx
// 아래 예시는 롤 룬과, 스펠을 받아오는 예시.
// queries 안에 배열로 넣어주면 된다.
const result = useQueries([
  {
    queryKey: ["getRune", riot.version],
    queryFn: () => api.getRunInfo(riot.version)
  },
  {
    queryKey: ["getSpell", riot.version],
    queryFn: () => api.getSpellInfo(riot.version)
  }
]);

useEffect(() => {
  console.log(result); // [{rune 정보, data: [], isSucces: true ...}, {spell 정보, data: [], isSucces: true ...}]
  const loadingFinishAll = result.some(result => result.isLoading);
  console.log(loadingFinishAll); // loadingFinishAll이 false이면 최종 완료
}, [result]);

```
* QueryCache : 쿼리에 대한 성공, 실패 전처리
```tsx
const queryClient = new QueryClient({
  queryCache: new QueryCache({
    onError: (error, query) => {
      console.log(error, query);
      if (query.state.data !== undefined) {
        toast.error(`에러 : ${error.message}`);
      },
    },
    onSuccess: data => {
      console.log(data)
    }
  })
});
```
* useMutation : post, update API
```tsx
import { useState, useContext, useEffect } from "react";
import loginApi from "api";
import { useMutation } from "react-query";

const Index = () => {
  const [id, setId] = useState("");
  const [password, setPassword] = useState("");

  const loginMutation = useMutation(loginApi, {
    onMutate: variable => {
      console.log("onMutate", variable);
      // variable : {loginId: 'xxx', password; 'xxx'}
    },
    onError: (error, variable, context) => {
      // error
    },
    onSuccess: (data, variables, context) => {
      console.log("success", data, variables, context);
    },
    onSettled: () => {
      console.log("end");
    }
  });

  const handleSubmit = () => {
    loginMutation.mutate({ loginId: id, password });
  };

  return (
    <div>
      {loginMutation.isSuccess ? "success" : "pending"}
      {loginMutation.isError ? "error" : "pending"}
      <input type="text" value={id} onChange={e => setId(e.target.value)} />
      <input
        type="password"
        value={password}
        onChange={e => setPassword(e.target.value)}
      />
      <button onClick={handleSubmit}>로그인</button>
    </div>
  );
};

export default Index;

```
* update후 get다시 실행 : useMutation - invalidateQueries
```tsx
const mutation = useMutation(postTodo, {
  onSuccess: () => {
    // postTodo가 성공하면 todos로 맵핑된 useQuery api 함수를 실행합니다.
    queryClient.invalidateQueries("todos");
  }
});

```
</details>

**Comment by Nahyun-Kang** [comment]
### 리액트 쿼리

- 리액트 쿼리란?
    - 데이터를 가져오는 과정에서 로딩과 에러 처리를 쉽게 구현할 수 있도록 하는 여러 기능 지원
    - 정해진 시간, 혹은 조건마다 서버 상태 데이터를 최신으로 가져오는 작업을 지원
    - 캐시(Cache)를 사용하여 매번 서버에서 데이터 가져올 필요 없이 유저에게 더 빠르게 서빙
    - 이외에도 Infinite Query, Optimistic Update 등 웹 앱에서 자주 사용하는 기능을 쉽게 구현할 수 있도록 하는 기 제공
    

### 리액트 쿼리가 하는 일!

- 캐싱... (프로그래밍에서 가장 어려운 작업일 수 있음)
- 동일한 데이터에 대한 여러 요청을 단일 요청으로 중복 제거하기
- 백그라운드에서 “오래된” 데이터 업데이트하기
- 데이터가 “오래된” 시기 파악하기
- 가능한 한 빨리 데이터에 업데이트 반영하기
- 페이지 매김 및 지연 로딩 데이터와 같은 성능 최적화
- 서버 상태의 메모리 및 가비지 컬렉션 관리
- 구조적 공유를 통한 쿼리 결과 메모화

**Comment by Jyophie** [comment]
### Next.js 프로젝트에서 React-query가 필요할까?

Next.js는 서버 사이드 렌더링(SSR)과 정적 사이트 생성(SSG) 지원을 통해 검색 엔진 최적화(SEO)에 유리한 환경과 초기 페이지 로딩 성능을 향상시켜준다. 이를 통해 우수한 사용자 경험을 제공할 수 있고, 앱 라우터 방식에서는 내장 fetch 함수를 페이지에서 비동기로 사용해 서버 사이드 렌더링을 구현하고 서버 액션을 가능하게 한다.

그렇다면 서버 상태 관리를 위한 React-query를 굳이 사용할 필요가 있을까? Next.js의 기본 제공 기능들이 매우 강력하기는 하지만, 모든 경우에 최적의 해결책을 제공하는 것은 아니다. 특히, 서버 상태 관리와 관련하여, React-query는 다음과 같은 몇 가지 이점을 제공한다.

- **캐싱과 상태 복구**: React-query는 자동으로 데이터를 캐싱하고, 네트워크 연결이 끊기거나 페이지를 새로 고칠 때 이전 상태를 복구할 수 있다. 이는 사용자 경험을 크게 향상시킬 수 있는 중요한 요소이다.
- **백그라운드 업데이트와 최적화**: 데이터를 백그라운드에서 자동으로 업데이트하며 사용자와의 상호작용을 방해하지 않고, 동시에 데이터 일관성을 유지한다.
- **통합된 오류 관리**: 오류 처리가 간소화되며, 각 쿼리의 상태에 따라 컴포넌트가 반응할 수 있도록 한다. 이는 디버깅 과정을 단순화하고 더 견고한 애플리케이션을 구축하는 데 도움이 된다.

이러한 이점을 고려할 때, React-query는 서버 상태를 관리하는 데 있어서 뛰어난 선택이 될 수 있다. 특히 대규모 프로젝트나 복잡한 데이터 흐름이 있는 애플리케이션에서 그 가치가 더욱 빛을 발한다. 결국, 사용하는 기술은 프로젝트의 요구사항과 팀의 선호도에 따라 달라질 수 있으며, Next.js와 React-query를 함께 사용함으로써 얻을 수 있는 시너지를 고려하는 것이 중요하다.

**Comment by Eugene-A-01** [comment]
**Q. ReactQuery를 왜 썼나요? 이점이 뭔가요?** 
서버에서 받아오는 데이터를 쉽게 관리하기 위해 사용했다.
리액트 쿼리를 이용하면 데이터의 fetching, caching, 요청 중복 제거, 서버데이터 동기화, 상태 등을 쉽게 파악하고 이용할 수 있었다. 
리액트 쿼리의 이점으로는 **효율적인 캐싱, 오래된 데이터 백그라운드 자동 업데이트, 페이징 처리와 로딩 지연 처리, 가비지컬렉션을 이용한 서버데이터 메모리관리,  중복요청 제거** 가 있다.

**Q. next.js를 채택했다면 사용하지 않을 수도 있지 않나요?** 
Next.js 역시 SSR과 서버 데이터를 가져오는 기능을 내장하고 있지만, React Query를 이용하면 **더 간단한 코드**로 데이터를 관리할 수 있다. 데이터 fetching 뿐만 아니라 캐싱, 에러처리, 중복요청 제거, 무한스크롤 구현 등을 Next.js만 사용했을때보다 훨씬 짧은 코드로 별도의 설정없이 즉시 사용가능하다.

(next.js도 fetch함수로 캐싱 자체는 가능함 주의)
```fetch('https://...', { cache: 'force-cache' })```

**Comment by hyeyoonS** [comment]
next.js는 내장 fetch함수를 제공하고 fetch로 캐시를 관리할 수 있습니다. 하지만 next.js에서 제공하는 fetch 만으로는 아직 next의 cache를 관리하는 게 어렵다는 의견을 보았습니다. 

공식적으로 Next14는 캐시된 값을 버리는(invalidate) 기술을 두 가지 지원해 주는데,

1. `server cache invalidate`
- fetch('path', { cache: 'no-store' } 로 항상 새로운 데이터를 받아올 수 있습니다.
- fetch('path', { tags: ['data'] }) 로 캐시를 특정할 수 있는 태그를 붙일 수 있습니다.
- revalidatePath, revalidateTag 함수로 fetch + GET method 의 결과값을 invalidate 할 수 있습니다.

2. `client cache invalidate` 
- router.refresh() : RQ에서 해당 페이지의 모든 쿼리를 invalidate하는 방식과 비슷합니다.클라이언트 렌더링 결과물만 바뀝니다. 캐시를 무효화하는 것이 아니라 페이지를 완전히 새로 로드하는 것이므로, 서버에서 새로운 HTML 페이지를 받아와서 클라이언트에게 다시 그리는 것과 유사합니다.

이 두 가지 방식을 조합해서 써야 하는데, client cache와 server cache를 생각하면서 잘 써야 하기 때문에 휴먼 에러가 다수 발생할 수 있습니다.

예시로, 

사용자가 게시글을 수정하면 → 검색 페이지의 검색 결과에서도 해당 게시글 내용이 수정되어야 하는 경우에,

`/search` 에서 `fetch('/getPost', { tags: [search] })` 로 데이터를 받고 (서버)

`/post/edit`경로에서 `revalidateTag('search')` 로 서버의 캐시를 invalidate (서버) 

하지만 클라이언트 컴포넌트에서 `router.refresh()` 를 사용해도 수정 사항이 반영되지 않습니다. 서버의 캐시만을 지웠을 뿐이기 때문입니다.….. 서버에서 최신 데이터를 다시 가져온 후  router.refresh()로 화면을 새로 그리거나 or state를 사용하여 데이터를 mutate하여야 합니다. 

```tsx
//state를 사용하여 데이터를 mutate하는 예시코드
import React, { useState } from 'react';

function PostComponent() {
  const [postData, setPostData] = useState(null);

  // 게시글 데이터를 업데이트하는 함수
  const updatePostData = (newData) => {
    setPostData(newData);
  };

  return (
    <div>
      <p>{postData}</p>
    </div>
  );
}
```
따라서 next.js에서 제공하는 fetch함수를 사용할 경우 서버와 클라이언트의 캐시를 각각 고려해야 하고, 코드가 매우 복잡해지기에  Client Component에서 데이터 Fetching 을 하는 경우 RQ를 쓰는 게 더 편하다는 의견을 따랐습니다. 

++ 또한 관련하여 학습을 할 때에  revalidate 함수를 사용한 경로에서 해당 경로의 client cache가 모두 날아가서, `화면 전체 렌더링`이 되는 이슈가 있었습니다. 임시적인 것으로 차기 버전에서는 수정 될 것이라고 합니다.

**Comment by HaydenDevK** [comment]
## React Query란
- 캐시를 통해 선언적으로 서버 상태와 클라이언트 상태를 동기화 해주는 도구이다.
- Redux의 단점을 보완한다.
  - 서버 상태를 Redux Store에 저장하는 것은 사실 Redux에서 추구하는 SSOT에 부합하지 않는다고 한다.
  - Redux는 보일러 플레이트 코드가 많다. (Redux-Toolkit 을 통해 어느정도 대응이 가능하지만)

## next.js를 사용한다면 React Query가 굳이 필요할까?
- 13 버전 이후로는 fetch() Web API를 기반으로 확장한 Data Fetching을 제공한다.
- 특히 React Query 처럼 캐싱 기능을 제공한다.
- 그럼에도 불구하고 React Query 사용 의의
  - query key를 통해 더욱 세부적으로 쿼리를 무효화할 수 있다. 
  - status와 fetchStatus를 제공하여 간편하게 로딩, 에러 처리를 할 수 있다.
  - Infinite Query, Optimistic Update 기능 구현이 간편하다.
- React Query 말고 다른 선택지는 없을까?
  - SWR이 있다.
    - 점유율 및 안정성, 추가 기능에 있어 React Query가 좀 더 선호도가 높다.
