### ISSUE TITLE
[02] Next.js의 주요 특징과 장점은 무엇이라고 생각하나요?

### ISSUE THREAD

**Issue by hyeyoonS** [QueenCards/ProjectAnalysis#2]
## ✏ 구술 답변 키워드
- 프리렌더링(SSR, SSG)
- 파일 기반 라우팅
- 코드 스플리팅
- 통합 API 라우팅
- CSS 모듈, CSS-in-JS 내장 지원
- 폴리필 자동 지원
- 데이터 패칭
- 핫 코드 리로딩
- Vercel과의 호환성

## ✏ 답변
Next.js는 React 라이브러리 기반의 프레임워크 입니다.

등장 배경

React의 등장과 함께 SPA(Single Page Application)이 대중화되면서 CSR이 주류가 되었습니다. 다만, 초기 로딩 지연 및 SEO의 문제점이 존재했고, 이를 개선하기 위해 등장한 것이 Next.js입니다. SSR과 SSG 및 하이드레이션을 통해 빠른 페이지 로딩, SEO 최적화, 효율적인 자원 활용 및 풍부한 사용자 인터렉션을 제공하여 개발 환경을 개선했습니다.

주요 특장점

- **프리 렌더링**: 처음에 빈 HTML을 가져와 Script를 로딩하는 CSR과 달리, 서버에서 프리 렌더링된 페이지를 가져와서 보여줍니다. SSR과 SSG 덕분에 사용자에게 더 빠르게 로딩된 페이지를 제공(UX 개선)하고 검색 엔진에 잘 노출될 수 있는 강화된 SEO를 제공합니다.

- **직관적인 파일 기반 라우팅**: 페이지 라우팅, 가장 최근 버전에는 폴더 기반 앱 라우팅을 제공하여 파일을 기반으로 쉽게 라우팅을 제공하고, 프로젝트 폴더 구조를 직관적으로 관리할 수 있습니다.

- **코드 스플리팅**: 코드 분할은 각 접근 지점에 필요한 청크(번들 보다 더 작은 단위)로 프로그램의 번들을 분할하는 과정을 말합니다. 프로그램을 실행하는데 꼭 필요한 청크 단위의 코드만 가져와서 로딩 시간 단축을 더욱 강화할 수 있습니다. Next.js는 코드 분할을 자체적으로 지원합니다.

- **통합된 API 개발**: Next.js는 개발자들이 애플리케이션 내에서 쉽게 서버리스 API 경로를 생성할 수 있도록 지원하여 풀 스택 애플리케이션 개발 프로세스를 간소화하고 프론트엔드와 백엔드 간의 원활한 통신을 가능하게 합니다.

- **내장된 CSS 및 JavaScript 지원**: Next.js에는 CSS 모듈 및 styled-components와 같은 인기 있는 CSS-in-JS 솔루션에 대한 내장 지원이 포함되어 있습니다. 또한 ES 모듈과 동적 임포트와 같은 현대적인 JavaScript 기능을 지원합니다.

- **폴리필**: 기본적으로 지원하지 않는 이전 브라우저에서 최신 기능을 제공하는 데 필요한 코드를 의미합니다. (자동적으로 지원 ex.바벨)

- **Data Fetching** : 메모이제이션, 데이터 캐싱 및 재요청 위한 확장된 fetch API.(페이지라우팅, 앱라우팅 버전에서 모두 지원)

- **Hot Code Reloading** : Next 개발 환경에서는 코드 변경 사항이 저장되면 응용 프로그램을 자동으로 다시 로드되므로, 개발 환경에서 번거롭게 새로고침을 할 필요가 없습니다.

- **Vercel과의 높은 호환성** : Vercel과 같은 클라우드 플랫폼에서 쉽게 배포할 수 있다.

참고

- 서버 사이드 렌더링(SSR) : SSR을 사용하면 각 요청에 대해 서버에서 HTML 페이지를 생성하여 초기 렌더링에 필요한 모든 데이터와 마크업을 포함할 수 있습니다. 이는 애플리케이션의 인지 성능을 향상시키고 검색 엔진이 콘텐츠를 쉽게 크롤링하고 인덱싱할 수 있도록 합니다.

- 정적 사이트 생성(SSG) : SSG를 사용하면 HTML 페이지가 빌드 시간에 생성되고 정적 에셋으로 제공되어 각 요청마다 서버 사이드 렌더링이 필요하지 않게 됩니다. SSG는 콘텐츠가 많은 웹사이트나 업데이트 빈도가 낮은 애플리케이션에 적합하며, 빠른 로딩 시간과 효율적인 캐싱을 가능하게 합니다.

**Comment by Nahyun-Kang** [comment]
Next.js는 다양한 기능을 제공하는데 정적 사이트 생성, 타입스크립트에 대한 기본 지원, 자동 폴리필 적용, 이미지 최적화, 성능 분석, 직관적인 라우팅 등이 있습니다.

- 폴리필: 기본적으로 지원하지 않는 이전 브라우저에서 최신 기능을 제공하는 데 필요한 코드를 의미합니다.
- 이미지 최적화 기능:
    - 이미지 리사이징
    - 레이아웃 시프팅 방지
    - 레이지 로딩을 기본적으로 지원
- 정적 사이트 생성: 빌드 타임에 생성된 파일을 클라이언트에 보내는 것, 인터랙티브한 기능을 수행할 수는 없지만 사용자의 화면에 매우 빠르게 노출시킬 수 있습니다.
- 직관적인 라우팅: 폴더에 있는 파일 명으로 라우팅을 쉽게 구현할 수 있습니다.
- 코드 스플리팅: 원하는 페이지에서 필요한 자바스크립트와 라이브러리만 렌더링하는 것을 의미합니다. 페이지에서 보여져야 하고, 필요한 것들끼리만 번들링함으로써 효율적으로 렌더링할 수 있습니다.

**Comment by Jyophie** [comment]
Next.js는 React 라이브러리 기반의 프레임워크 입니다. 

1. 등장 배경
React의 등장과 함께 SPA(Single Page Application)이 대중화되면서 CSR이 주류가 되었습니다. 다만, 초기 로딩 지연 및 SEO의 문제점이 존재했고, 이를 개선하기 위해 등장한 것이 Next.js입니다. SSR과 SSG 및 하이드레이션을 통해 빠른 페이지 로딩, SEO 최적화, 효율적인 자원 활용 및 풍부한 사용자 인터렉션을 제공하여 개발 환경을 개선했습니다.

2. 주요 특장점

- **프리 렌더링**: 처음에 빈 HTML을 가져와 Script를 로딩하는 CSR과 달리, 서버에서 프리 렌더링된 페이지를 가져와서 보여줍니다. SSR과 SSG 덕분에 사용자에게 더 빠르게 로딩된 페이지를 제공(UX 개선)하고 검색 엔진에 잘 노출될 수 있는 강화된 SEO를 제공합니다.
- **직관적인 파일 기반 라우팅**: 페이지 라우팅, 가장 최근 버전에는 폴더 기반 앱 라우팅을 제공하여 파일을 기반으로 쉽게 라우팅을 제공하고, 프로젝트 폴더 구조를 직관적으로 관리할 수 있습니다.
- **코드 스플리팅**: 코드 분할은 각 접근 지점에 필요한 청크(번들 보다 더 작은 단위)로 프로그램의 번들을 분할하는 과정을 말합니다. 프로그램을 실행하는데 꼭 필요한 청크 단위의 코드만 가져와서 로딩 시간 단축을 더욱 강화할 수 있습니다. Next.js는 코드 분할을 자체적으로 지원합니다.

**Comment by olseul** [comment]
Next.js는 사용자가 실제로 방문하는 페이지의 코드만 로드합니다. 이는 불필요한 코드 로딩을 줄여 성능을 향상시킵니다. 

TypeScript 설정을 자동으로 처리해주고, 바로 사용할 수 있는 환경을 제공합니다. 이를 통해 개발자는 타입 안정성을 높이고 에러를 사전에 감지합니다.

pages 디렉토리에 파일을 추가함으로써 자동으로 해당 파일 경로에 맞는 라우트가 설정됩니다. 복잡한 라우팅 설정을 별도로 관리할 필요가 없어 개발이 간편해집니다.

**Comment by HaydenDevK** [comment]
1. **하이브리드 렌더링** : 페이지 특성에 따라 SSG, SSR, ISR, CSR을 선택적으로 적용할 수 있습니다.
2. **프리 렌더링** 
: 기본적으로 모든 페이지를 프리 렌더링하여 빠른 초기 로딩 속도, 빈 화면이 아닌 초기 화면을 제공하여 사용자 경험을 향상시키며, SEO에 유리합니다.
3. **코드 스플리팅** : 자동으로 코드 스플리팅을 수행하고 명시적인 dynamic 문법을 지원하여 로딩 속도를 개선하고 사용자 경험을 향상시킵니다.
4. **이미지 최적화** : Image 컴포넌트를 통해 자동으로 이미지 최적화를 수행하여 성능 및 사용자 경험을 향상시킵니다.
5. **파일 시스템 기반의 라우팅** : 별도의 라이브러리 없이 규칙에 맞게 폴더와 파일만 생성하면 간편하게 페이지 간 이동을 구현할 수 있습니다.

**Comment by wise-Ag** [comment]
1. **Routing** :  레이아웃, 중첩 라우팅, 로딩 상태, 오류 처리 등을 지원하는 파일 시스템 기반 라우터.
2. **Rendering** : 클라이언트 컴포넌트, 서버 컴포넌트로 CSR, SSR제공.
3. **Data Fetching** : 메모이제이션, 데이터 캐싱 및 재요청 위한 확장된 fetch API.
4. **Optimizations** : 사용자 경험을 향상시키기 위한 이미지, 글꼴 및 스크립트 최적화.

**Comment by hyeyoonS** [comment]
### 프리렌더링

프리렌더링은 웹페이지 로딩 이전에 하는 렌더링(웹브라우저가 HTML을 받아오기 이전에 하는 렌더링)을 말합니다. 프리렌더링의 종류는 정적 생성(Static Generation)과 서버 사이드 렌더링(ServerSideRendering)으로 나눌 수 있는데, 이러한 프리렌더링을 통해 초기 로딩속도를 향상시키고, 검색엔진을 최적화 할 수 있습니다. 

### 라우팅 시스템

페이지 경로를 파일/폴더 구조를 통해 자동으로 설정할 수 있습니다. 별도의 라우팅 설정 없이 편리하게 페이지를 추가할 수 있고, 프로젝트 구조를 명확하게 구성할 수 있습니다.

### Hot Code Reloading

Next 개발 환경에서는 코드 변경 사항이 저장되면 응용 프로그램을 자동으로 다시 로드되므로, 개발 환경에서 번거롭게 새로고침을 할 필요가 없습니다.

### 최적화의 이점이 있는 다양한 기능들

- next/Image

Image 컴포넌트를 통해 이미지 크기를 자동으로 최적화합니다. 또한 이미지를 곧바로 로드하지 않고, lazy-loading을 통해 뷰포트에 이미지가 필요한 순간에 이미지를 가져와 최적화 합니다. 

- next/Font

 빌드 타임에 폰트를 다운받아 미리 정적 파일로 만들어 놓습니다. 따라서 유저가 어플리케이션을 실행할 때 별도의 요청이 필요하지 않아 유저 경험을 향상시킬 수 있습니다.

- next/Link

클라이언트 측 라우팅을 사용하여 페이지 간의 부드러운 전환을 구현할 수 있습니다.
이때 페이지는 서버에서 미리 렌더링 되고, 사용자가 이동을 할 때 새로운 페이지를 서버로 요청하지 않고 클라이언트에서만 렌더링 되도록 합니다. 이로 인해 사용자 경험이 향상되고 페이지 간의 전환 속도가 빨라집니다.
또한 next/link는 HTML의 **`<a>`** 요소를 렌더링하기 때문에 검색 엔진 최적화(SEO)에도 도움이 됩니다.

**Comment by Eugene-A-01** [comment]
1. **SSR** : 기본적으로 서버사이드렌더링을 지원하여 초기로딩속도와 검색엔진최적화를 개선시킬 수 있습니다.

2. **API 라우팅** : pages/api 디렉토리를 이용해 서버리스 API 엔드포인트를 만들 수 있습니다.

3. **라우팅** : 페이지 라우팅이나 앱라우팅 방식을 이용해서 파일시스템 기반의 라우팅으로 디렉토리안에 파일을 생성해서 쉽게 라우팅 경로를 생성하고 관리할 수 있습니다.

4. **이미지 최적화와 렌더링 최적화** : next/Image를 이용해 이미지 크기와 렌더링 시점을 최적화할 수 있고, next/Link를 이용해 페이지 리렌더링없이도 마치 SPA처럼 부분 렌더링으로 페이지 이동을 할 수 있다.

**Comment by kanglocal** [comment]
1. SEO에 유리하다. (서버사이드렌더링이기때문에)
초기 로딩시간을 단축하여 사용자경험을 향상시킨다.(서버사이드 렌더링이기때문에)
2. 코드 스필리팅(초기 로드시 필요한 최소한의 코드만 다운로드), 환경변수, 타입스크립트 지원등의 기능으로 개발 생산성을 높인다.
3. Vercel과 같은 클라우드 플랫폼에서 쉽게 배포할 수 있다.
4. 서버리스 아키텍처와 함께 사용할 수 있다.
5. 라우팅, 바벨, 웹팩등의 설정과 백엔드의 미들웨어, SEO, SSR등의 많은 것을 해결해준다.

요약? : 핫 리로딩, 오토매틱 라우팅, 싱글 파일 컴포넌트, 서버렌더링, 코드 스필리팅, 타입스크립트.

#### +) Next.js의 단점은?
폴더 기반 라우팅을 하다보니 예약파일이 많아 프로젝트가 커지면 복잡해진다.
페이지 이동시 새로운 페이지를 요청하기때문에 깜빡임이 존재할 수 있다.
미완성된 신기능이 도입되어 종종 에러가 생길 수 있다.

#### +) 총평은?( 본인이 프로젝트를 총괄하게되면 뭐쓸건지? 규모 작은거면? SEO필요없으면? )
신기술이 지속적으로 나와 팔로우업하기 어려울 수 있다.(러닝커브가 있을 수 있다.)
하지만 SSR의 장점들이 굉장히 크다.
