### ISSUE TITLE
[20] 런타임과 컴파일타임에 대해서 설명해주세요

### ISSUE THREAD

**Issue by hyeyoonS** [QueenCards/ProjectAnalysis#23]
## 📎 질문
런타임과 컴파일타임에 대해서 설명해주세요

## ✏ 구술 답변 키워드
- 런타임과 컴파일 타임의 간단한 정의
- 런타임과 컴파일의 서술
- 자바스크립트는 인터프리터 언어
- 소스코드에서 바이트 코드로 변환될 때 과정
- 최근 자바스크립트 실행 방식 (JIT)

## ✏ 서술 답변
# 런타임과 컴파일 타임

- 소프트웨어 프로그램 개발의 서로 다른 두 계층의 차이를 설명하기 위한 용어
- **컴파일타임:** 기계어코드로 변환되어 실행 가능한 프로그램이 되는 과정.
- **런타임:** 컴파일과정을 마친 프로그램은 사용자에 의해 실행되어지며, 응용프로그램이 동작되어지는 때

## 컴파일(Compile)이란?

- 컴퓨터는 0과 1을 통해서만 명령을 실행할 수 있지만 개발자가 프로그래밍에 사용하는 언어들은 0과 1로 이루어진 형태가 아니다.
- 개발자가 프로그램을 위해 작성한 소스 코드를 다른 프로그램이나 기계가 처리하기 용이한 형태로 바꾸는 과정을 말한다.
    - 컴파일 언어: Java, C, C++ 등이 컴파일 언어, 실행되기 위해서는 반드시 컴파일 과정을 거쳐야 한다.
    - 스크립트 언어: 컴파일 과정 없이 기계어로 번역되는 즉시 동작하도록 되어있다.
        - 따라서 컴파일 과정은 필요하지 않지만 작동 시에는 컴파일 언어에 비해 느리다는 단점이 있다.

### 일반적인 컴파일 과정

- 아래 이미지는 예시 (c언어)

![Untitled](https://github.com/QueenCards/ProjectAnalysis/assets/142777396/5b75964f-b341-465b-bad8-761c1a83dcb0)

- 넓은 의미에서의 컴파일 과정 : 전처리 과정 → 컴파일 과정 → 어셈블리 과정 → 링킹 과정 총 4 단계
    1. `전처리 과정(Pre-processing)` : `전처리기(Preprocessor)`를 통해 `소스 파일(.c)`을 전처리된 `소스 코드 파일(.i)`로 변환
    2. `컴파일 과정(Compilation)` : `컴파일러(Compiler)`를 통해 `소스 코드 파일(.i)`을 ``어셈블리어 파일(.s)로 변환
    3. `어셈블리 과정(Assembly)` : `어셈블러(Assembler)`를 통해 `어셈블리어 파일(.s)`를 `오브젝트 파일(.o)`로 변환
    4. `링킹 과정(Linking)` : `링커(Linker)`를 통해 `오브젝트 파일(.o)들`을 묶어 `실행 파일`로 변환
- 흔히 위의 4단계를 빌드한다고 하고, 빌드 과정에 컴파일과 링킹이 포함된다고 말한다.

### 컴파일러

- 프로그래밍 언어를 기계어로 빠르게 컴파일할 수 있도록 미리 번역해둔 프로그램

### 인터프리터

- 프로그래밍 언어를 한 줄 씩 읽어서 실행하는 프로그램 (런타임 환경에서 기계어로 바로 번역)

### **JIT 컴파일러**

- Just In Time, 실시간(런타임) 컴파일 기법
- 프로그램을 실행하는 시점에 바이트코드를 기계어로 번역하는 역

### Object Code

- 컴파일러나 어셈블러에 의해 생성된 파일
- 기계어나 기계어 수준의 바이너리 코드로 해석된 코드를 의미

### 코드 종류

- **바이트 코드:** 가상머신이 이해할 수 있는 중간 레벨로 컴파일 한 코드 (JavaScript에서 가상머신은 브라우저와 node에서 사용되는 V8등을 의미)
- **바이너리 코드:** 컴퓨터가 이해할 수 있는 언어. 하지만 링커에 의해 메모리 주소값을 반영하고 CPU가 직접 해독하고 실행할 수 있도록 수정되어야 기계어가 되는 것이기 때문에 가장 기계어와 유사한 레벨의 코드지만 완전한 기계어는 아니다. (Object 파일(목적파일)은 바로 실행될 수 없다. 코드가 여러 파일로 나눠져있기 때문에 이 파일을 연결 시키고, 목적파일을 하나로 통합시켜 하나의 실행파일로 만들기 위해 링크 과정이 필요.
- **어셈블리어:**  니모닉 기호(mnemonic symbol)을 정해 사람이 쉽게 제어할 수 있도록 한 것으로 기계어에 일대일 대응된다.
    - 컴퓨터는 0과 1만 이해할 수 있는데 사람이 이해하기 어렵기 때문에 사람이 쉽게 기억하기 위해 기계어와 일대일 대응한 것이 니모닉 기호. 이 니모닉 기호를 정하여 일련의 명령어를 나타낸 것이 어셈블리어.
- **기계어:** CPU가 직접 해독하고 실행할 수 있는 비트 (0과 1)로 쓰인 컴퓨터 언어

### hotspot

- 코드 중 자주 반복되어서 실행되는 부분

### Compiler vs InterPreter

- **인터프리터 방식:** 실행 중에 한 줄 씩 읽어가면서 바로 실행하는 인터프리터 방식.
    - 코드가 번역된 후 컴퓨터로 전달되어 바로 실행된다.
    - 프로그램을 실행할 때 필요하므로 프로그램을 실행시키기 위해서 인터프리터가 설치되어 있어야 한다.
    - 서로 다른 운영체제에서 자유롭게 실행시킬 수 있다.
    - 오버헤드가 가해진다: 인터프리터는 실행 중에 코드의 각 줄이 해석되어야 한다.
    - 반면 인터프리터는 해석과 실행을 동시에 수행하므로 실행 속도는 느리다. 하지만 한 줄 씩 실행할 때마다 에러를 확인할 수 있어 실시간 코드 수정이 가능하다.
- **정적 컴파일 방식:** 실행 전에 컴파일 하는 정적 컴파일 방식
    - 인터프리터와 달리 코드를 바로 실행하지 않고, 번역이 완료된 코드를 저장하고 언제든지 실행시킬 수 있다.
    - 한 번 컴파일 되었다면 컴파일된 프로그램만 있으면 실행 가능하므로 원본 소스코드 필요 X
    - 운영체제에 맞춰서 컴파일이 되기 때문에, 다른 운영체제에서는 동작하지 않는다. 다른 운영체제에서도 실행하기 위해 재컴파일을 진행해야 한다. 하지만, 컴파일러는 컴파일된 프로그램이 더 효과적으로 수행되도록 운영체제의 사양에 맞게 최적화할 수 있다.
    - 성능에 장점이 있다:  컴파일러로 컴파일된 프로그램은 운영체제가 바로 읽고  실행할 수 있다.
    - 컴파일러의 경우 실행 속도가 빠르지만, 전체 코드를 컴파일한 후에 에러를 확인할 수 있어 디버깅이 불편하다. 수정사항이 발생하면 전체 코드를 다시 컴파일 해야 한다.
- **JITC(동적 번역)(참고):** 실행 하는 시점에 바이트코드를 기계어로 컴파일하는 기법
    - 인터프리터와 정적 컴파일을 혼합한 방식. 프로그램 실행 시점에 인터프리터 방식으로 기계어 코드를 생성하면서 그 코드를 캐싱하여, 같은 함수가 여러번 불릴 때마다 매번 기계어 코드를 생성하는 것을 방지한다.

### JavaScript는 인터프리터 언어이다.

- 인터프리터 언어: JavaScript, HTML, python, Ruby
- 컴파일 언어: JAVA /  C

![Untitled (1)](https://github.com/QueenCards/ProjectAnalysis/assets/142777396/ddbd9985-5298-46fb-ab0b-41117b1c3016)

### 소스코드에서 바이트 코드로

- 자바스크립트는 기본적으로 text 형식이기 때문에 코드를 실행하기 전에 해석하는 컴파일 과정 필요
- 먼저 소스코드를 파싱하여 중간언어(IR)인 바이트코드 형태로 변환

- 바이트코드로 변환하는 과정
    1. 코드를 의미있는 조각으로 나누는 **렉싱(토크나이징Tokenizing)**
    2. 코드를 트리구조로 나타내는 AST로 만드는 **파싱**
    3. VM(브라우저, V8)이 실행할 수 있도록 AST를 **바이트 코드**로 변환하는 **컴파일**
        - 여기서 AST를 바이트 코드로 변환하는 것은 Ignition이라는 **인터프리터.**
    4. 바이트코드를 실행하면서 최적화 해야 하는 데이터 (자주 쓰이는 코드)는 최적화한다. ⇒ Optimized Machine Code를 생성한다.
- 바이트 코드를 바로 실행한다.
    - Ignition이 만든 바이트 코드를 실행함으로써 자바스크립트 코드가 동작

![Untitled (2)](https://github.com/QueenCards/ProjectAnalysis/assets/142777396/262d2084-fe1a-4843-a702-1d819b4c339c)

- hotspot 관련: Java는 연산이 많은 프로그램이 많음 반면, JavaScript는 주로 웹 페이지의 layout을 건드리거나 사용자 입력에 반응하는 방식의 프로그램이 많다. JavaSciprt는 상대적으로 hotsopt이 매우 적다.

### JavaScript 엔진은 JIT 컴파일 방식을 사용한다.

- 최근 JavaScript 엔진들은 대부분 **adaptive compilation** 방식
    - 모든 코드에 일괄적으로 같은 수준의 최적화를 적용하는 것이 아니라 반복 수행되는 정도에 따라 서로다른 최적화 수준을 적용하는 방식
    - 기본적으로 모든 코드는 처음에 인터프리터로 해석. → 자주 반복되는 부분이 발견되면 그 부분에 대해서만 JIT 적용하여 native code로 변환.
    - **Ignition이 인터프리터, TurboFan이 JIT 컴파일러**

## 런타임이란?

- 런타임이란? 어떤 프로그램이 실행되고 있는 동안의 동작.
- 해당 프로그램이 필요한 시스템 자원 등을 할당받고 실제로 시스템 자원을 사용해서 처리를 하고 있는 것.
- 프레임워크, 컴포넌트, 라이브러리 등이 메모리에 로드되었을 때 시작한다.
- 런타임을 위해 운영체제는 실행이 처음 시작될 때부터 끝날 때까지 모든 프로그램에 필요한 만큼의 메모리, 프로세서, 입출력 리소스를 할당한다.

### 런타임 환경?

- 이 런타임이 일어나기 위해 해당 프로그램이 시스템 자원을 사용하기 위하여 시스템 자원에 접근할 수 있도록 해주는 실행환경

- 자바스크립트 런타임의 주요 구성 요소 : 자바스크립트 엔진, 웹API, 콜백 큐, 이벤트 루프, 렌더 큐

### 컴파일 에러와 런타임 에러
[컴파일 에러]
컴파일 에러는 프로그램이 컴파일링되는 과정에서 발생하는 에러입니다.
- Syntax Error
- Type 체크 에러
- 파일 참조 오류

[런타임 에러]
소스코드가 이미 실행가능한 프로그램으로 성공적으로 컴파일이 되었더라도 여전히 프로그램의 실행중에 버그를 일으킬 수 있습니다. 이렇게 프로그램의 실행중에 발생하는 형태의 오류를 런타임 에러라고 한다.

0 나누기 오류
Null 참조 오류
메모리 부족 오류

### 3. 타입스크립트 컴파일
추상화 단계가 다른 고수준 언어가 저수준 언어로 변환되는 과정을 말합니다.

타입스크립트는 tsc라고 불리는 컴파일러를 통해 자바스크립트 코드로 변환됩니다.
하지만 타입스크립트는 고수준 언어(타입스크립트) ⇒ 고수준 언어(자바스크립트)로 변환되는 것이기 때문에 컴파일이 아니라 트랜스파일이라고 부르기도 합니다.
또한 이 과정은 소스코드를 또다른 소스코드로 변환하는 것이므로 소스 대 소스 컴파일러 라고 지칭하기도 합니다.
트랜스파일의 대표적인 예시로는 자바스크립트 ES6이상의 문법을 ES5이하의 문법으로 변환하는 바벨을 들 수 있습니다.
타입스크립트는 . ts확장자가 붙은 파일을 찾아내서 컴파일 한 다음 ⇒ .js 확장자가 붙은 자바스크립트 파일을 만들어냅니다.
타입스크립트 컴파일러는 소스코드를 해석해서 AST(최소 구문 트리)를 만들고 이후 타입 확인을 거친 다음에 결과 코드를 생성합니다.

💡 AST (Abstract Syntax Tree)

컴파일러가 소스 코드를 해석하는 과정에서 생성된 데이터 구조
컴파일러는 어휘적 분석(Lexical analysis)과 구문 분석(Syntax analysis)을 통해 소스코드를 노드 단위의 트리 구조로 구성합니다.

### 참고자료

[[https://velog.io/@wish/JavaScript는-어떻게-컴파일될까](https://velog.io/@wish/JavaScript%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%BB%B4%ED%8C%8C%EC%9D%BC%EB%90%A0%EA%B9%8C)](https://velog.io/@wish/JavaScript%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%BB%B4%ED%8C%8C%EC%9D%BC%EB%90%A0%EA%B9%8C)

[[https://prefer2.tistory.com/entry/Javascript-자바스크립트-엔진-자바스크립트-런타임](https://prefer2.tistory.com/entry/Javascript-%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%97%94%EC%A7%84-%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EB%9F%B0%ED%83%80%EC%9E%84)](https://prefer2.tistory.com/entry/Javascript-%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EC%97%94%EC%A7%84-%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EB%9F%B0%ED%83%80%EC%9E%84)

**Comment by olseul** [comment]
컴파일타임 (Compile-time)
컴파일타임은 소스 코드가 기계어로 변환되는 동안의 시기를 의미합니다. 이 과정은 일반적으로 컴파일러에 의해 수행됩니다. 컴파일타임 동안에는 다음과 같은 작업이 이루어집니다:

구문 분석(Syntax Checking): 소스 코드가 문법적으로 올바른지 확인합니다. 문법 오류가 있는 경우, 컴파일러는 오류 메시지를 출력합니다.
타입 체크(Type Checking): 변수와 함수의 데이터 타입이 올바르게 사용되었는지 검사합니다. 예를 들어, 정수 변수에 문자열을 할당하려고 하면 컴파일 오류가 발생합니다.
코드 최적화(Code Optimization): 컴파일러는 코드를 최적화하여 실행 속도를 높이고 메모리 사용을 줄입니다.
코드 생성(Code Generation): 최종적으로 소스 코드가 기계어 또는 중간 코드로 변환됩니다. 기계어는 CPU가 직접 실행할 수 있는 명령어이고, 중간 코드는 JIT 컴파일러에 의해 런타임에 기계어로 변환될 수 있습니다.
컴파일타임 예시

int main() {
    int a = 5;
    int b = "hello"; // 컴파일 오류: 타입 불일치
    return 0;
}
위의 C++ 코드에서 int b = "hello";는 컴파일타임 오류를 발생시킵니다. 문자열을 정수 변수에 할당하려고 했기 때문입니다.

런타임 (Runtime)
런타임은 프로그램이 실행되는 동안의 시기를 의미합니다. 런타임 동안에는 다음과 같은 작업이 이루어집니다:

메모리 할당(Memory Allocation): 프로그램이 실행되면서 필요한 메모리를 할당합니다. 예를 들어, 객체 생성 시 힙 메모리에 공간이 할당됩니다.
동적 타입 검사(Dynamic Type Checking): 일부 언어에서는 실행 시간에 타입 검사가 이루어질 수 있습니다. 예를 들어, 자바스크립트에서는 변수의 타입이 런타임에 결정됩니다.
예외 처리(Exception Handling): 실행 중에 발생하는 예외를 처리합니다. 예를 들어, 파일을 열 때 파일이 존재하지 않으면 런타임 오류가 발생할 수 있습니다.
JIT 컴파일(Just-In-Time Compilation): 일부 언어에서는 런타임에 코드를 컴파일합니다. 예를 들어, 자바와 같은 언어는 바이트코드를 JIT 컴파일러를 통해 기계어로 변환합니다.
런타임 예시

public class Main {
    public static void main(String[] args) {
        int[] arr = new int[5];
        System.out.println(arr[10]); // 런타임 오류: 배열 인덱스 초과
    }
}
위의 자바 코드에서 arr[10]은 배열의 범위를 초과하여 런타임 오류(ArrayIndexOutOfBoundsException)를 발생시킵니다.

**Comment by hyeyoonS** [comment]
# 자바스크립트의 런타임과 타입스크립트의 컴파일

## 1. 런타임과 컴파일타임

### 🤔컴파일타임이 뭐지?

개발자가 작성한 소스코드가 컴파일 과정을 거쳐 컴퓨터가 인식할 수 있는 기계어 코드(바이트코드)로 변환되어 실행할 수 있는 프로그램이 되는 과정 

### 🤔런타임이 뭐지?

컴파일 과정을 마친 응용 프로그램이 메모리에 적재되어, 사용자에 의해 실행되는 과정

---

## 2. 자바스크립트 런타임

자바스크립트가 실행되는 환경을 의미합니다.

크롬, 사파리와 같은 `인터넷 브라우저`와 `Node.js` 등이 있습니다.

자바스크립트 런타임의 주요 구성 요소 : 자바스크립트 엔진, 웹API, 콜백 큐, 이벤트 루프, 렌더 큐

---

## 3. 타입스크립트 컴파일

추상화 단계가 다른 고수준 언어가 저수준 언어로 변환되는 과정을 말합니다.

- 타입스크립트는 tsc라고 불리는 컴파일러를 통해 자바스크립트 코드로 변환됩니다. 
하지만 타입스크립트는 고수준 언어(타입스크립트) ⇒ 고수준 언어(자바스크립트)로 변환되는 것이기 때문에 컴파일이 아니라 `트랜스파일`이라고 부르기도 합니다.
    - 또한 이 과정은 소스코드를 또다른 소스코드로 변환하는 것이므로 `소스 대 소스 컴파일러` 라고 지칭하기도 합니다.
    - 트랜스파일의 대표적인 예시로는 자바스크립트 ES6이상의 문법을 ES5이하의 문법으로 변환하는 `바벨`을 들 수 있습니다.

타입스크립트는 . ts확장자가 붙은 파일을 찾아내서 컴파일 한 다음 ⇒ .js 확장자가 붙은 자바스크립트 파일을 만들어냅니다.
타입스크립트 컴파일러는 소스코드를 해석해서 AST(최소 구문 트리)를 만들고 이후 타입 확인을 거친 다음에 결과 코드를 생성합니다.

> **💡 AST (Abstract Syntax Tree)** 
> - 컴파일러가 소스 코드를 해석하는 과정에서 생성된 데이터 구조
> - 컴파일러는 어휘적 분석(Lexical analysis)과 구문 분석(Syntax analysis)을 통해 소스코드를 노드 단위의 트리 구조로 구성합니다.
>

**Comment by HaydenDevK** [comment]
## 컴파일타임
- 소스 코드를 분석하는 동안
- 컴파일 에러 : 컴파일되는 과정 중에 Syntax error, 파일 참조 오류 등의 문제로 컴파일이 방해되어 발생하는 에러
## 런타임
- (컴파일 과정을 마친) 프로그램이 실행(실제 데이터를 입력받아 결과를 출력) 중인 동안
- 런타임 에러 : 이미 컴파일이 완료되어 프로그램이 실행중임에도 불구하고, 의도치 않은 예외상황으로 인해 프로그램 실행 중에 발생하는 오류

**Comment by Jyophie** [comment]
### 컴파일 타임 (Compile Time)

컴파일 타임은 소스 코드를 실행 가능한 프로그램으로 변환하는 과정이 이루어지는 시간입니다. 이 과정에서는 코드가 컴파일러에 의해 번역되어 기계어 또는 중간 언어로 변환됩니다. 컴파일 타임에는 다음과 같은 작업이 수행됩니다:

- 구문 검사(Syntax Checking): 소스 코드의 문법이 올바른지 검사합니다.
- 타입 검사(Type Checking): 변수와 함수의 타입이 올바르게 사용되었는지 확인합니다.
- 코드 최적화(Code Optimization): 컴파일러는 코드의 실행 속도를 높이기 위해 다양한 최적화 작업을 수행합니다.
- 코드 생성(Code Generation): 최종적으로 기계어 또는 중간 언어로 변환된 코드를 생성합니다.


### 런타임 (Run Time)

런타임은 프로그램이 실제로 실행되는 시간을 의미합니다. 이 시점에서 컴파일된 프로그램이 메모리에 로드되고, CPU에 의해 실행됩니다. 런타임에는 다음과 같은 작업이 수행됩니다:

- 프로그램 실행(Program Execution): 컴파일된 코드가 실행됩니다.
- 동적 메모리 할당(Dynamic Memory Allocation): 프로그램이 실행되는 동안 필요한 메모리를 동적으로 할당합니다.
- 런타임 오류(Runtime Errors): 프로그램 실행 중 발생할 수 있는 오류를 처리합니다. 예를 들어, 배열 인덱스 초과, null 포인터 참조 등이 있습니다.

**Comment by wise-Ag** [comment]
사람이 프로그램을 위해 작성한 소스코드를 기계가 이해할 수 있는 **기계어로 변환하는 과정**을 컴파일이라고 합니다.
런타임이란 **프로그램이 실행되는 환경**이나 **동작되는 동안의 시간**을 말합니다.

### 컴파일러 언어와 인터프리터 언어
컴파일 과정 수행 여부에 따라 컴파일러 언어와 인터프리터 언어로 구분됩니다.
컴파일러 언어 : C, C++, C#, JAVA
컴파일 단계와 실행 단계가 분리되어 있어 컴파일 한 후 생성된 실행파일을 실행합니다.
인터프리터 언어에 비해 코드 실행 속도가 빠릅니다.
다만, 코드 수정이 있을 때마다 다시 컴파일(re-compile) 해야하는 번거로움이 있습니다.

인터프리터 언어 :  Python, JavaScript, Ruby
컴파일 과정 없이 소스코드를 한 줄 한 줄 읽고 바이트 코드로 변환하여 바로 수행합니다.
컴파일 자체에 소요하는 시간이 없고 코드 수정 시 재컴파일의 번거로움이 없습니다.
실행파일이 생성되지 않기 때문에 매 실행시마다 코드를 해석하는 인터프리트 과정이 반복되어 컴파일러 언어에 비해 수행 속도가 느립니다.

### 컴파일 에러와 런타임 에러
컴파일 에러는 프로그램이 컴파일링되는 과정에서 발생하는 에러입니다.
- Syntax Error
- Type 체크 에러
- 파일 참조 오류

소스코드가 이미 실행가능한 프로그램으로 성공적으로 컴파일이 되었더라도 여전히 프로그램의 실행중에 버그를 일으킬 수 있습니다. 이렇게 프로그램의 실행중에 발생하는 형태의 오류를 런타임 에러라고 한다.
* 0 나누기 오류
* Null 참조 오류
* 메모리 부족 오류

**Comment by Eugene-A-01** [comment]
컴파일이란
- 넓은 의미의 컴파일 = 전처리 + _컴파일_ + 어셈블리 + 링킹
- 좁은 의미의 컴파일 : 전처리 완료된 소스코드(주석제거, 헤더파일 삽입 등)가 CPU가 이해할 수 있는 어셈블리어(0과1로 이루어진 기계어와 1대1 대응되는 저수준 언어) 변환하는 작업 

컴파일 타임이란, 넓은 의미의 컴파일이 실행되는 과정.
즉 고차원 프로그래밍 언어로 작성된 소스코드가 0과 1로 이루어진 기계어로 변환되는 과정이다.
컴파일타임에 발생할 수 있는 오류는 타입오류나 문법적 오류, 파일 참조 오류 같이 기계어로 변환을 불가능하게 하는 상황 때문에 발생한다.

런타임이란, 이렇게 컴파일을 마쳐 기계어로 변환된 프로그램이 메인메모리 위에 적재되고 CPU 할당을 받아 프로세스가 실행되고 있는 과정이다.
런타임 오류는 0으로 나누게 되거나 null을 참조하게 되거나 메모리가 부족해지는 등 프로그램이 실행 중에 마주하는 예상치 못한 예외상황 또는 충돌로 발생한다.
