### ISSUE TITLE
[23] 디바운스와 쓰로틀링에 대해서 설명해주세요 . 프로젝트의 어느 부분에서 사용했나요?

### ISSUE THREAD

**Issue by hyeyoonS** [QueenCards/ProjectAnalysis#26]
## 📎 질문
디바운스와 쓰로틀링에 대해서 설명해주세요 . 프로젝트의 어느 부분에서 사용했나요?

## ✏ 구술 답변 키워드
- 디바운스와 쓰로틀링이 무엇인 지 간단히 설명
- 디바운스와 작동방식에 대해 설명
- 쓰로틀링과 작동방식에 대해 설명
- 프로젝트 사용 부분 설명

## 디바운스와 쓰로틀링이 뭘까?
디바운스(Debouncing)와 쓰로틀링(Throttling)은 자주 발생하는 이벤트(예: 스크롤, 리사이즈, 키 입력 등)를 제어하여 성능을 최적화하기 위한 기술입니다. 두 방법 모두 이벤트가 지나치게 많이 발생하여 성능이 저하되는 것을 방지하는 데 사용되지만, 그 작동 방식은 다릅니다.

## 디바운스
디바운스는 이벤트가 연속적으로 발생할 때, 특정 시간 동안 이벤트가 발생하지 않을 때까지 대기한 후, 마지막에 한 번만 실행되도록 하는 방법입니다. 이를 통해 연속된 이벤트 호출을 하나로 줄일 수 있습니다.

## 디바운스 작동방식
- 이벤트가 발생할 때마다 타이머를 초기화합니다.
- 특정 시간 동안 추가 이벤트가 발생하지 않으면 콜백 함수를 실행합니다.
- 추가 이벤트가 발생하면 타이머를 재설정하고, 다시 대기합니다.

## 쓰로틀링
쓰로틀링은 이벤트가 연속적으로 발생할 때, 일정한 간격으로 이벤트를 처리하도록 하는 방법입니다. 이를 통해 이벤트가 일정 주기마다 실행되도록 제한할 수 있습니다.

예를 들어, 사용자가 스크롤할 때마다 이벤트를 처리하지 않고, 일정 시간 간격으로 한 번씩만 이벤트를 처리합니다.

### 쓰로틀링 작동 방식
특정 시간 내에 (호출이 있으면) 첫번째 호출만 실행하고, 특정 시간 동안 후속 호출을 무시한다.

### 프로젝트 사용
- 피드 스크롤 이벤트에서 사용

**Comment by Nahyun-Kang** [comment]
### 디바운스와 쓰로틀링

프로그램의 기능에 무리를 주지 않기 위해 사용하는 최적화 기법

### 디바운싱

- 연이어 호출되는 함수들 중 마지막 함수(혹은 처음)만 호출하는 것

### 쓰로틀링

- 일정 시간 동안 이벤트 핸들러를 한 번만 실행하도록 하는 것
- 쓰로틀링은 연속해서 발생하는 이벤트에 대해서 일정 주기마다 최대 한번의 이벤트만 실행되도록 하는 것.
- ex) 스크롤 이벤트 처리 시, 스크롤 이벤트가 지나치게 빈번하게 발생하면 성능 저하 발생 가능. 쓰로틀링 적용시, 일정 주기마다 스크롤 이벤트 처리하여 성능 개선 가능

**Comment by hyeyoonS** [comment]
## **디바운싱과 쓰로틀링**

디바운싱과 쓰로틀링은 `성능을 목적으로 자바스크립트의 이벤트를 제어`하기 위해 사용되는 기법입니다.

## **디바운싱**

- 자바스크립트에서의 디바운싱은 `마지막으로 발생한 이벤트를 기준으로` 특정 time이 지난 후 `하나의 이벤트만 실행`되도록 합니다.

- **사용 예시:** 검색 기능의 키 이벤트(input)
    - 검색 버튼을 누르지 않아도 사용자가 입력한 값이 변경될 때마다 자동으로 검색 요청을 보내는 기능을 만든다고 한다면, 사용자가 검색어를 다 입력하지 않았을 때에도 요청이 보내지게 되므로 비효율적입니다.
    - 이러한 경우에 디바운싱을 적용하면 사용자의 입력이 끝나고 일정 시간이 지난 후에 검색 요청이 1번만 보내지므로 성능을 향상시킬 수 있습니다.
    
- **디바운싱 예시코드**
    
    ```tsx
    //1. js예시코드
    
    const inputElement = document.querySelector('#ID값');
    const DELAY = 500;
    const handleChange = () => {
      console.log('요청!');
    }
    
    let timer;
    
    inputElement.addEventListener('input', () => {
      if (timer) clearTimeout(timer);
      timer = setTimeout(handleChange, DELAY);
    });
    
    ```
    
- 이벤트가 발생할 때마다 timer 변수에 콜백 함수를 반환하는 setTimeout 함수를 값으로 할당합니다.
    
    ⇒time 이내에 새로운 이벤트가 발생할 때마다 타이머를 초기화 해준다고 이해하면 된다!
    
- time 이내에 새로운 이벤트가 발생한다면 clearTimeout을 해줌으로써 콜백 함수는 실행되지 않으며, 발생하지 않으면 setTimeout은 콜백 함수를 실행하게 됩니다.


```tsx
//2. React에서의 예시코드

import { useCallback, useEffect } from 'react';

const useDebounceFunc = (func: () => void, delay: number, deps: any[]) => {
  const callback = useCallback(func, deps);

  useEffect(() => {
    const timer = setTimeout(() => callback(), delay);
    return () => clearTimeout(timer);
  }, [callback, delay]);
};

export default useDebounceFunc;

```

## **쓰로틀링**

자바스크립트에서의 쓰로틀링은 짧은 시간 내에 과도한 이벤트 실행으로 인해 발생하는 성능 저하를 막기 위해 일정한 `time slice를 주기로 이벤트가 한 번만 실행되도록` 제한하는 것을 말합니다.  

- **사용 예시:**  scroll, resize, drag, mouse 이벤트, 애니메이션 등
    - 쓰로틀링을 적용하게 되면 불필요한 이벤트 실행 횟수를 줄일 수 있어 성능을 향상시킬 수 있습니다**.**
    - 스크롤 이벤트의 경우, 크롬 기준 2px 단위로 이벤트가 발생하게 되므로, 사용자가 1초에 1000px의 스크롤을 하게 되는 경우에는 약 500번의 이벤트가 발생되므로 성능에 좋지 않습니다. 
    이 때 time = 100 간격으로 이벤트가 실행되도록 쓰로틀링을 적용하면 실행 횟수를 10번으로 줄일 수 있습니다.

- **쓰로틀링 예시 코드**
    
    ```tsx
    // 1. js 예시 코드 
    const DELAY = 500;
    const handleScroll = () => {
      timer = null;
      console.log('스크롤!');
    }
            
    let timer;  
       
    window.addEventListener('scroll', () => {
      if (!timer) timer = setTimeout(handleScroll, DELAY);
    });
    
    ```
    
    - 이벤트가 발생했을 때, timer 변수의 값이 비어있다면 콜백 함수를 반환하는 setTimeout 함수를 값으로 할당합니다. 그리고 콜백 함수 내에서는 timer를 null 값으로 초기화 해준다.
    
    ⇒ 이러한 방법으로 time 이내에 최대 1번의 콜백 함수만 실행하도록 보장할 수 있습니다.
    

## 디바운싱과 쓰로틀링을 도와주는 **`lodash`**

lodash에서는 디바운싱과 쓰로틀링을 쉽게 적용할 수 있도록 debounce, throttle 메소드를 제공합니다.

- **사용 방법:** 디바운싱 혹은 쓰로틀링을 적용할 함수를 메소드로 감싸고 2번째 인자로 delay 값을 전달

```tsx
//디바운싱 예제

import { debounce } from 'lodash';

const DebounceInput = () => {
  const handleChange = debounce(({ target }) => {
    console.log('debounce', target.value);
  }, 500);

  return <input type="text" onChange={handleChange} />;
};

export default DebounceInput;

```

```tsx
//쓰로틀링 예제

import { throttle } from 'lodash';

const ThrottleInput = () => {
  const handleChange = throttle(({ target }) => {
    console.log('throttle', target.value);
  }, 500);

  return <input type="text" onChange={handleChange} />;
};

export default ThrottleInput;

```

**Comment by HaydenDevK** [comment]
- 연속적으로 함수를 호출한 경우에 실행을 제어하는 성능 최적화 기법들이다.
## 디바운스
- 마지막 호출 후 특정 시간 만큼 호출이 멈춰야, 멈추기 전 마지막 호출만 실행하고 이전 호출은 무시한다.
- ex) 검색어 입력이 끝난 후에 함수를 호출하는 검색창 기능 구현
## 쓰로틀링
- 특정 시간 내에 (호출이 있으면) 첫번째 호출만 실행하고, 특정 시간 동안 후속 호출을 무시한다.
- ex) 스크롤 이벤트 관련 기능

**Comment by Jyophie** [comment]
디바운스(Debouncing)와 쓰로틀링(Throttling)은 자주 발생하는 이벤트(예: 스크롤, 리사이즈, 키 입력 등)를 제어하여 성능을 최적화하기 위한 기술입니다. 두 방법 모두 이벤트가 지나치게 많이 발생하여 성능이 저하되는 것을 방지하는 데 사용되지만, 그 작동 방식은 다릅니다.

### 디바운스 (Debouncing)

디바운스는 이벤트가 연속적으로 발생할 때, 특정 시간 동안 이벤트가 발생하지 않을 때까지 대기한 후, 마지막에 한 번만 실행되도록 하는 방법입니다. 이를 통해 연속된 이벤트 호출을 하나로 줄일 수 있습니다.

#### 예시:
- **입력 필드의 자동완성**: 사용자가 입력할 때마다 자동완성 API를 호출하지 않고, 입력이 멈추고 일정 시간이 지나면 API를 호출합니다.

#### 작동 방식:
1. 이벤트가 발생할 때마다 타이머를 초기화합니다.
2. 특정 시간(예: 300ms) 동안 추가 이벤트가 발생하지 않으면 콜백 함수를 실행합니다.
3. 추가 이벤트가 발생하면 타이머를 재설정하고, 다시 대기합니다.

#### 코드 예시:
```javascript
function debounce(func, wait) {
  let timeout;
  return function(...args) {
    clearTimeout(timeout);
    timeout = setTimeout(() => func.apply(this, args), wait);
  };
}

// 사용 예시
const handleInput = debounce((event) => {
  console.log(event.target.value);
}, 300);

document.getElementById('inputField').addEventListener('input', handleInput);
```

### 쓰로틀링 (Throttling)

쓰로틀링은 이벤트가 연속적으로 발생할 때, 일정한 간격으로 이벤트를 처리하도록 하는 방법입니다. 이를 통해 이벤트가 일정 주기마다 실행되도록 제한할 수 있습니다.

#### 예시:
- **스크롤 이벤트 처리**: 사용자가 스크롤할 때마다 이벤트를 처리하지 않고, 일정 시간 간격으로 한 번씩만 이벤트를 처리합니다.

#### 작동 방식:
1. 이벤트가 처음 발생할 때 콜백 함수를 즉시 실행합니다.
2. 이후 특정 시간 간격(예: 200ms)이 지나기 전에는 이벤트를 무시합니다.
3. 시간이 지나면 다시 이벤트를 처리할 수 있게 됩니다.

#### 코드 예시:
```javascript
function throttle(func, limit) {
  let inThrottle;
  return function(...args) {
    if (!inThrottle) {
      func.apply(this, args);
      inThrottle = true;
      setTimeout(() => inThrottle = false, limit);
    }
  };
}

// 사용 예시
const handleScroll = throttle(() => {
  console.log('Scroll event');
}, 200);

window.addEventListener('scroll', handleScroll);
```

### 차이점 요약
- **디바운스(Debouncing)**: 마지막 이벤트가 발생한 후 일정 시간 동안 추가 이벤트가 발생하지 않을 때 콜백 함수가 실행됩니다. 예를 들어, 사용자가 키 입력을 멈춘 후 일정 시간이 지나야 API를 호출합니다.
- **쓰로틀링(Throttling)**: 일정 시간 간격으로 이벤트를 처리합니다. 예를 들어, 스크롤 이벤트를 일정 주기마다 한 번씩만 처리합니다.

디바운스와 쓰로틀링은 모두 이벤트가 빈번하게 발생하는 상황에서 성능을 최적화하는 데 유용합니다. 각각의 상황에 맞게 적절히 사용하면 애플리케이션의 성능을 향상시킬 수 있습니다.

**Comment by wise-Ag** [comment]
디바운싱과 쓰로틀링은 연속적으로 실행되는 함수를 제어하여 성능을 최적화하는 기법입니다.

## 디바운싱
지정된 딜레이 기간중 처음 혹은 마지막 함수만 실행하는 기법입니다.
처음 함수를 호출하는 것을 **leading edge**, 마지막 함수만 실행하는 것을 **trailing edge**라고 합니다.

- 함수가 호출될 때마다 타이머를 초기화합니다.
- 함수 호출 후 딜레이 기간이 지나면 함수를 실행합니다.
- 함수 호출 후 딜레이 내에 또 함수를 호출할 경우 타이머는 초기화되어 다시 딜레이기간이 발생합니다.
줄을 서다가 이탈하면 다시 맨 뒤부터 줄을 서야하는 것과 비슷합니다.

_사용예시_
- 검색어 자동 입력
- 은행 송금 버튼을 두 번 클릭해도 한 번만 실행됨

## 쓰로틀링
일정 시간마다 한 번만 함수를 실행하는 기법으로 디바운싱과 비슷하지만 매 호출마다 타이머를 초기화시키지 않는다는 점에서 차이점이 있습니다.

- 함수 호출이 스로틀을 트리거합니다.
- 딜레이 내 추가 호출은 무시됩니다.
- 딜레이가 만료되면 호출이 실행되고 프로세스가 반복됩니다.

_사용예시_
- 스크롤 이벤트

**Comment by Eugene-A-01** [comment]
**Q. 디바운스와 쓰로틀링에 대해서 설명해주세요 .**

디바운스와 쓰로틀링은 웹에서의 과도한 이벤트 발생을 방지하고 이벤트핸들러의 호출을 제어하기 위한 기술

디바운스
- 연속으로 호출 된 함수 중 마지막에 호출된 함수만 실행되도록 하는것 
- 지정된 딜레이 안에 여러번 발생한 이벤트 중 마지막 이벤트를 **딱 한 번** 발생시킴
- 함수 호출을 지연시키는 것 ! (예를 들어 딜레이는 1초이고 이벤트가 딱 한 번 발생했다면 하나뿐이라도 1초뒤에 실행시킴, 딜레이가 끝나기 전 이벤트가 또 발생했다면 이전 호출이 취소되고 딜레이는 초기화되는 형식. 딜레이가 끝나야 함수호출이 된다. 즉 딜레이가 1초고 0.99초마다 이벤트가 100번 발생한다면 99초 뒤 100번째 이벤트만 함수 호출함)
- 사용자의 입력을 받는 상황(검색, 유효성 검사, 자동완성 등)에 사용된다.

쓰로틀링
- 마지막 함수가 호출된 이후 일정 시간이 지나기 전에 다시 호출되지 않도록 하는것. 
- 여러번 발생한 이벤트 중 설정한 주기에 해당하는 이벤트**들** 발생함 (주기 제어)
- 디바운스와 달리 딜레이를 초기화 시키지 않는다. 
- 무한 스크롤, 마우스 움직임 등에 사용된다.


**Q. 프로젝트의 어느 부분에서 사용했나요?**

스크롤을 사용하는 곳에 useThrottle 커스텀 훅을,
사용자 입력을 받는 곳에 useDebounce 커스텀 훅을 사용했다.
