### ISSUE TITLE
[28] 긴 로딩시간을 처리하는 방법에 대해서 알려주세요. 

### ISSUE THREAD

**Issue by hyeyoonS** [QueenCards/ProjectAnalysis#31]
## 📎 질문
긴 로딩시간을 처리하는 방법에 대해서 알려주세요.

### 1️⃣ 서버 측 개선

**TTFB(Time to First Byte) 개선**
- **요청 수 줄이기**: 불필요한 요청을 제거하고, HTTP/2 또는 HTTP/3를 사용하여 다중 요청을 병렬 처리
- **전송 크기 줄이기**: 압축을 통해 전송 데이터를 줄임
- **DB 쿼리 최적화**: 인덱스 추가, 쿼리 최적화, 불필요한 데이터 호출 제거
- **서버 애플리케이션 로직 최적화**: 효율적인 코드 작성, 비동기 처리
- **서버 하드웨어 업그레이드**: 더 빠른 CPU, SSD 사용, 메모리 확장
- **리다이렉트 최소화**: 불필요한 리다이렉트 제거
- **캐시 활용**: 브라우저 캐싱, 서버 측 캐싱 (Redis, Memcached)

</br>

### 2️⃣ 클라이언트 측 개선

**FCP(First Contentful Paint) 개선**
- **CSS/JS 파일 제거 및 최소화**: 사용하지 않는 CSS와 JavaScript 코드 제거, 파일 크기 최소화
- **코드 압축 및 축소**: HTMLMinifier, CSSNano, Terser 등을 사용하여 파일 크기 줄이기
- **코드 스플리팅**: 초기 로딩 시 불필요한 코드 로딩 방지

**이미지 최적화**
- **이미지 압축**: TinyPNG, ImageOptim, Squoosh 등의 도구 사용
- **적절한 포맷 선택**: JPEG(사진), PNG(투명도 필요), WebP(다목적)
- **반응형 이미지 사용**: `<img>` 태그의 `srcset` 속성 사용

**콘텐츠 전송 네트워크(CDN) 사용**
- **CDN 설정**: Cloudflare, AWS CloudFront, Akamai 등의 CDN 서비스 활용
- **동적 콘텐츠 캐싱**: CDN을 통해 동적 콘텐츠도 캐싱

**비동기 로딩**
- 비동기 로딩은 웹 페이지의 특정 자원(예: JavaScript 파일, CSS 파일, 이미지 등)을 웹 페이지가 로드되는 동안 비동기적으로 로드하는 기법. 초기 페이지 로딩이 차단되지 않으며, 사용자가 페이지와 상호작용할 수 있는 시간을 단축할 수 있음
- **JavaScript 비동기 로딩**: `<script src="path/to/script.js" async>` 또는 `<script src="path/to/script.js" defer>` 사용
- **CSS 비동기 로딩**: `<link rel="preload" href="path/to/styles.css" as="style" onload="this.onload=null;this.rel='stylesheet'">` 사용

**지연 로딩(Lazy Loading)**
- 웹 페이지의 콘텐츠를 필요할 때만 로드하는 기술. 이를 통해 초기 로딩 시간과 데이터 전송량을 줄여 웹 페이지 성능을 향상시키고 사용자 경험을 개선할 수 있음
- **이미지 지연 로딩**: `<img loading="lazy" src="path/to/image.jpg">` 속성 사용
- **Intersection Observer API**: JavaScript의 Intersection Observer API 사용 (요소가 뷰포트 내에 들어오거나 나갈 때 콜백을 실행할 수 있으므로, 뷰포트에 들어왔을 때 이미지나 다른 리소스를 로드하는 데 매우 유용)

</br>

### 3️⃣ 사용자 경험 개선

**로딩 인디케이터 도입**
- **1초 미만**: 로딩 인디케이터 도입하지 않음
- **1초~3초**: 스피너 사용
- **3초 이상**: 프로그레스바 사용

**애니메이션 사용**
- **로딩 애니메이션**: 로딩 중 브랜드 이미지, 팁, 정보 등을 보여주는 애니메이션
- **대표 예시**: 크롬 공룡게임

**스켈레톤 UI**
- **동적 스켈레톤 UI**: 애니메이션이 적용된 스켈레톤 UI 사용으로 대기 시간 단축 효과

**낙관적 UI**
- **낙관적 업데이트**: 이벤트가 발생한 것처럼 보여주고, 실패 시 알림

</br>

### 4️⃣ 로딩 시간 최적화

**초기 로딩 최적화**
- **SSG(Static Site Generation) 및 SSR(Server-Side Rendering) 활용**: 초기 로딩을 빠르게 함
- **코드 스플리팅**: Webpack, Gulp 등을 사용하여 번들링 및 코드 스플리팅

**Next.js 및 React 최적화**
- **Next.js App Router의 캐싱 활용**
- **React Query의 캐싱 활용**

</br>

### 5️⃣ 로딩 시간 UI/UX 개선

**React의 Suspense 활용**
- **Next.js `loading.js` 사용**
- **React Query의 Optimistic Updates**: 사용자가 요청을 보낸 후 즉시 결과가 반영된 것처럼 보여줌
- **React Query의 다양한 로딩 상태 활용**: 로딩, 에러, 성공 상태에 따라 UI를 다르게 표시

**Comment by Eugene-A-01** [comment]
**1. 긴 로딩시간을 짧게 단축하는 방법**
- TTFB(time to first byte) 개선 : 
서버 성능과 직결된 문제. 요청수 줄이고 전송크기 줄이기, db쿼리 최적화, 서버 애플리케이션 로직 최적화, 서버 하드웨어 업그레이드 등 TTFB를 개선하기 위해선 서버측에서 할 일이 많음. 프론트엔드 개발자로서 할수있는 개선법에는 리다이렉트 발생 부분을 최대한 줄이기, 캐시를 잘 활용하는 방법이 있다.
- FCP(first contentful paint) 개선 : 
CSS, js 제거 및 최소화


**2. 로딩시간이 짧은 것처럼 사용자 경험을 개선하는 방법**
- 로딩 인디케이터(스피너, 프로그레스바) 도입 
(1초-3초:스피너, 3초이상 프로그레스바, 1초미만 도입하지 않음 권장)
- 애니메이션 사용 (애니메이션 적용된 로딩, 브랜드 이미지, 팁이나 정보 보여주기 등 -> 대표적으로 크롬 공룡게임)
- 스켈레톤 UI (애니메이션이 적용된 동적인 스켈레톤일때 대기시간을 더 짧게 느낀다고 함)
- 낙관적 UI (이미 이벤트가 발생한것처럼 보여주고, 실패했을때는 따로 알려주는 식의 UI)


[참고](https://eunjinii.tistory.com/44)

**Comment by HaydenDevK** [comment]
## 로딩 시간 최적화
- 초기 로딩이 빠른 SSG, SSR 활용
- 이미지 최적화
- 코드 스플리팅
- Next.js App router의 캐싱 활용
- React query의 캐싱 활용

## 로딩 시간 UI/UX 개선
- React의 Suspense>
- Next의 loading.js
- React query의 Optimistic Updates
- React query의 다양한 로딩 상태 활용
