### ISSUE TITLE
[30] PWA가 뭔가요? PWA에 대해서 아는 대로 설명해주세요.

### ISSUE THREAD

**Issue by hyeyoonS** [QueenCards/ProjectAnalysis#33]
## 📎 질문
 PWA가 뭔가요? PWA에 대해서 아는 대로 설명해주세요. 

## ✏ 구술 답변 키워드
- Progressive Web App
- 웹과 앱의 차이 [좋은참고자료](https://medium.com/@howyoujini/web-app-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%82%AC%EC%9A%A9%EC%9E%90%EB%A5%BC-%EC%84%A4%EB%93%9D%ED%95%98%EB%8A%94%EA%B0%80-2ed36233b5a6)
- PWA 적용의 장점과 단점
- PWA 적용 방법
- 서비스워커와 알림

## ✏ 서술 답변

**1. PWA란?**
네이티브앱처럼 사용할 수 있는 웹 어플리케이션
설치, 푸시알림, 오프라인동작 등 네이티브앱에서만 가능했던 기능들을 웹사이트에서도 이용할 수 있다.

**2. PWA 장점**
- **앱스토어 출시를 위한 프로세스가 없다** + 플레이스토어나 앱스토어에 내는 수수료도 없다.
- 네이티브앱 개발을 위한 언어, 프레임워크가 아닌 일반적인 웹기술로 PWA만들 수 있고, 기존 웹으로 개발된 웹사이트를 앱으로 만들 수 있기 때문에 마이그레이션, 유지관리가 쉽다.
- **검색엔진을 통해서도 검색이 가능**하다.
- 원한다면 앱스토어를 통해서도 PWA 배포가 가능하다.
- **푸시알림**으로 사용자 재접속을 유도할 수 있다.

**3. PWA 단점**
- 아직 IOS는 PWA에 필요한 기술들을 사파리에서 지원하지 않는 경우가 있음. (설치 프롬프트)
- 하드웨어 직접 접근이 어려움 (카메라, 지문인식, 센서 등을 활용하는데 제한있을 수 있음 + 네이티브앱에 비해 성능이 떨어질 수 있음)
- 게임같은 고사양 애플리케이션은 PWA로 어려움. 
- (개인적인 생각) : '홈화면 추가하기'라는 절차가 아직 대다수의 사용자에게는 익숙하지 않은 방식의 앱설치 방법이라고 느낌. 설치 유도가 쉽지 않음

**4. PWA 적용방법**
[PWA 적용할때 참고했던 포스팅](https://gxxrxn.github.io/nextjs-pwa/)
1. **next-pwa 설치** 및 next.config.js에 적용
2. OS, 이미지 크기별 아이콘 파일 추가하기
3. **manifest.json 파일** 만들고 layout.tsx의 head에 적용해주기
`{
  "theme_color": "#C9E5FF",
  "background_color": "#C9E5FF",
  "display": "standalone",
  "scope": "/",
  "start_url": "/",
  "name": "\ub9ac\uc2a4\ud2f0\uc6e8\uc774\ube0c",
  "short_name": "\ub9ac\uc2a4\ud2f0",
  "icons": [
    {
      "src": "icons/pwa/windows11/SmallTile.scale-100.png",
      "sizes": "71x71"
    },
    {
      "src": "icons/pwa/windows11/SmallTile.scale-125.png",
      "sizes": "89x89"
    },`
`<link rel="manifest" href="/manifest.json" />`

**추가. PWA 적용 대표 서비스**
트위터, 스타벅스, 우버, 핀터레스트 등

**Comment by Jyophie** [comment]
## PWA(Progressive Web App)

PWA(Progressive Web App)는 웹 애플리케이션의 최신 개발 패턴으로, 네이티브 앱과 유사한 사용자 경험을 제공하는 웹 애플리케이션을 의미합니다. PWA는 HTML, CSS, JavaScript의 기술을 사용하여 개발됩니다.

### PWA의 주요 구성 요소

1. **서비스 워커(Service Worker)**
   - 브라우저와 웹 서버 사이에 위치한 스크립트로, 네트워크 요청을 가로채고 캐싱을 관리
   - 오프라인 모드 지원, 푸시 알림, 백그라운드 동기화 등의 기능을 제공함

2. **웹 앱 매니페스트(Web App Manifest)**
   - PWA의 메타데이터(앱 이름, 아이콘, 시작 URL, 테마 색상 등)를 포함한 JSON 파일
   - 사용자가 PWA를 홈 화면에 추가할 때 네이티브 앱처럼 보이게 하는 데 사용 됨

3. **HTTPS**
   - 보안된 HTTPS 프로토콜을 사용하여 PWA를 제공해야 함
   - 서비스 워커의 설치와 실행을 위해 필수

### PWA의 이점

1. **향상된 성능**: 캐싱과 서비스 워커를 통해 더 빠른 로딩 시간과 부드러운 사용자 경험을 제공합니다.
2. **오프라인 지원**: 오프라인에서도 콘텐츠에 접근할 수 있어 네트워크 의존성을 줄입니다.
3. **네이티브 앱과 유사한 경험**: 홈 화면에 추가, 푸시 알림, 전체 화면 모드 등 네이티브 앱과 유사한 사용자 경험을 제공합니다.
4. **검색 가능성**: 웹 기술을 사용하여 검색 엔진에 쉽게 인덱싱됩니다.
5. **크로스 플랫폼**: 다양한 디바이스와 운영체제에서 일관된 경험을 제공합니다.
