### ISSUE TITLE
[32] ReactQuery의 GC 타임, stale time에 대해서 설명해주세요. 또 prefetchQuery를 사용한 경험이 있나요? 

### ISSUE THREAD

**Issue by hyeyoonS** [QueenCards/ProjectAnalysis#35]
## 📎 질문
(1) ReactQuery의 GC 타임, stale time에 대해서 설명해주세요.
(2) prefetchQuery를 사용한 경험이 있나요?

## ✏ 구술 답변 키워드
(1) 
**Stale Time**
- React Query에서 데이터를 '신선한'(fresh) 상태로 간주하는 시간 (기본 값 0)
- 데이터가 서버에서 마지막으로 가져온 이후로 지정된 시간 동안 신선하다고 간주되며, 이 기간 동안에는 재요청을 하지 않습니다.
<br>

**Garbage Collection Time**
- GC 타임은 캐시에 저장된 데이터가 메모리에서 제거될 때까지의 시간 (기본 값 5분)
- 이 시간 동안 사용되지 않은 데이터는 자동으로 가비지 컬렉션(GC)되어 메모리에서 해제됩니다.

(2)
**prefetchQuery가 뭔가요?**
- 데이터가 실제로 필요하기 전에 사전에 데이터를 가져오고 캐시에 저장하는 방법 중 하나! 
- prefetchQuery를 호출해서 특정 데이터를 클라이언트에 캐싱해두고, 동일한 쿼리키를 사용하여 접근하여 캐싱된 데이터를 재사용 합니다.

<br>

**prefetchQuery를 사용하면 좋은 예시?**
- 블로그 게시물 목록 (상품 목록) 에서 상세 페이지로 이동할 때
- SNS에서 사용자가 친구 목록을 보다가 특정 친구를 클릭해서 친구의 프로필을 보려고 할 때

---
---
## ✏ 서술 답변
# (1) ReactQuery의 GC 타임, stale time에 대해서 설명해주세요.

## gcTime과 staleTime의 플로우 예시!

- `gcTime` 은 기본값 5분, `staleTime` 은 기본값 0초를 가정합니다.
1. `A`라는 queryKey를 가진 A 쿼리 인스턴스가 `mount`
2. 네트워크에서 데이터 fetch하고, 불러온 데이터는 A라는 queryKey로 `캐싱`함
3. 이 데이터는 `fresh`상태에서 `staleTime(기본값 0)` 이후 `stale` 상태로 변경됨
4. A 쿼리 인스턴스가 `unmount`됨
5. 캐시는 `gcTime(기본값 5min)` 만큼 유지되다가 `가비지 콜렉터(GC)`로 수집됨
6. 만일, gcTime 지나기 전이고, A 쿼리 인스턴스 fresh한 상태라면 새롭게 mount되면 캐시 데이터를 보여준다! 

## staleTime과 gcTime

- stale은 용어 뜻대로 `썩은`이라는 의미이다. 즉, 최신 상태가 아니라는 의미이다.
- fresh는 뜻 그대로 `신선한`이라는 의미이다. 즉, 최신 상태라는 의미이다.

```tsx
const {
  data,
  // ...
} = useQuery({
  queryKey: ["super-heroes"],
  queryFn: getAllSuperHero,
  gcTime: 5 * 60 * 1000, // 5분
  staleTime: 1 * 60 * 1000, // 1분
});
```

## 1. staleTime: `(number | Infinity)`
    - staleTime은 데이터가 `fresh에서 stale` 상태로 변경되는 데 걸리는 시간입니다.
     만약 staleTime이 `3000`이면 fresh 상태에서 `3초` 뒤에 stale로 변환됩니다.
    - `fresh` 상태일 때는 쿼리 인스턴스가 새롭게 mount 되어도 네트워크 요청(fetch)이 일어나지 않습니다.
    - staleTime의 기본값은 `0`이기 때문에 일반적으로 fetch 후에 바로 stale이 됩니다.
## 2. gcTime: `(number | Infinity)`
    - 데이터가 사용하지 않거나, `inactive` 상태일 때 `캐싱 된 상태로` 남아있는 시간(밀리초)입니다.
    - 쿼리 인스턴스가 unmount 되면 데이터는 `inactive 상태로 변경`되며, 캐시는 `gcTime`만큼 유지됩니다.
    - gcTime이 지나면 `가비지 콜렉터`로 수집됩니다.
    - gcTime이 지나기 전에 쿼리 인스턴스가 다시 mount 되면, 데이터를 fetch 하는 동안 캐시 데이터를 보여줍니다.
    - gcTime은 staleTime과 관계없이, 무조건 `inactive` 된 시점을 기준으로 캐시 데이터 삭제를 결정합니다.
    - gcTime의 기본값은 `5분`이고, SSR 환경에서는 `Infinity`이입니다.
    - 
---

# (2) prefetchQuery를 사용한 경험에 대해서 알려주세요. 
## 1. prefetchQuery가 뭐지?

- Prefetching은 데이터가 실제로 필요하기 전에 사전에 데이터를 가져오고 캐시에 저장하는 프로세스를 말합니다. 데이터가 실제로 필요한 시점에 미리 캐시에 데이터가 존재하도록 해서, 페이지 로딩 속도를 높이고 유저 경험을 향상시킬수 있습니다.
- react query에서는 `queryClient.prefetchQuery`을 통해서 손쉬운 prefetch 기능을 제공합니다

- 짚고 넘어가야 할 것 : prefetch를 하는 방법은  `queryClient.prefetchQuery` 가 유일하지 않다!
예시: 함수의 생명주기 안에서 데이터를 차례대로 로드해야할 때 --- 쿼리를 사용하고 결과를 무시하기

```ts
function Article({ id }) {
  const { data: articleData, isPending } = useQuery({
    queryKey: ['article', id],
    queryFn: getArticleById,
  })

  // Prefetch
  useQuery({
    queryKey: ['article-comments', id],
    queryFn: getArticleCommentsById,
    // Optional optimization to avoid rerenders when this query changes:
    notifyOnChangeProps: [],
  })

  if (isPending) {
    return 'Loading article...'
  }

  return (
    <>
      <ArticleHeader articleData={articleData} />
      <ArticleBody articleData={articleData} />
      <Comments id={id} />
    </>
  )
}

function Comments({ id }) {
  const { data, isPending } = useQuery({
    queryKey: ['article-comments', id],
    queryFn: getArticleCommentsById,
  })

  ...
}
```

## 2. prefetchQuery의 동작 방식

1. **데이터 페칭**:
    - prefetchQuery를 호출하면 지정된 쿼리 키와 쿼리 함수를 사용하여 데이터를 가져옵니다.
2. **React Query 캐시에 저장**:
    - 가져온 데이터는 React Query의 클라이언트 캐시에 저장됩니다. 이 캐시는 브라우저의 메모리에 저장되며, 동일한 쿼리 키를 사용하는 컴포넌트가 데이터에 접근할 때 재사용됩니다.
3. **서버 사이드에서 데이터 준비 (SSR/SSG)**:
    - prefetchQuery는 페이지를 렌더링하기 전에 데이터를 미리 가져와서 캐시에 저장해둡니다.
4. **캐시된 상태 직렬화**:
    - 서버 사이드 렌더링(SSR) 또는 정적 사이트 생성(SSG) 이전에, `dehydrate` 로 캐시된 상태를 JSON으로 직렬화하여 HTML과 함께 클라이언트로 전달합니다.
    - 클라이언트 측에서는 `HydrationBoundary`를 사용하여 직렬화된 상태를 복원(hydrate)하고, 동일한 캐시를 사용합니다.

### **1) `차단한 유저 목록`에 접근할 때**

- **flow :** 마이펫 캐러셀 ⇒ 구독자 목록 ⇒ 차단한 유저 목록
- 이 때 구독자 목록에 반드시 접근해야 차단한 유저 목록으로 이동할 수 있으므로, 구독자 목록이 보여지는 시점에 차단한 유저 목록의 데이터를 prefetch합니다.

<img src="https://github.com/QueenCards/ProjectAnalysis/assets/144667455/40dbb6ed-f44d-4044-b1b6-4d772e95d732" width="450">

```tsx
//쉬운 예시 
"use server";

import { HydrationBoundary, QueryClient, dehydrate } from "@tanstack/react-query";
import { getMyInvitations } from "@/app/_api/invitation";
import { getPet, getCode } from "@/app/_api/pets";
import { cookies } from "next/headers";
import PetSubscriberList from "@/app/settings/_components/Pet-Subscriber-List";

const Page = async () => {
  const queryClient = new QueryClient();
  const petId = Number(cookies().get("petId")?.value);
  await queryClient.prefetchQuery({ queryKey: ["my-invitations", petId], queryFn: () => getMyInvitations() });
  await queryClient.prefetchQuery({ queryKey: ["petInfo", petId], queryFn: () => getPet(petId) });
  await queryClient.prefetchQuery({ queryKey: ["inviteCode", petId], queryFn: () => getCode() });

  const dehydratedState = dehydrate(queryClient);

  return (
    <HydrationBoundary state={dehydratedState}>
      <PetSubscriberList petId={petId} />
    </HydrationBoundary>
  );
};

export default Page;
```

### **2) 다이어리 목록에서 다이어리 상세 내용에 접근할 때**

- **flow:** 마이펫 일기(목록) ⇒ 목록 중 하나 클릭
- DiaryDetail컴포넌트에 접근하기 전 DiaryDetailPage에서 petId와 diaryId를 prefetch합니다.

> (cf. 마이펫일기 옆 **친구의일기** 에 접근할때도 동일한 flow입니다~ 다만 무한스크롤로 구현되어있어 **prefetchInfiniteQuer**y를 사용합니다)
> 

<img src="https://github.com/QueenCards/ProjectAnalysis/assets/144667455/22130a0f-d086-406f-9074-0b90e3e63f44" width="500">

```tsx

//다이어리 상세페이지: 서버사이드에서 diary라는 이름으로 petId, diaryId 프리페치

import { getDiary } from "@/app/_api/diary";
import DiaryDetail from "@/app/diary/_components/DiaryDetail";
import { HydrationBoundary, QueryClient, dehydrate } from "@tanstack/react-query";
import { cookies } from "next/headers";

const DiaryDetailPage = async ({ params: { id } }: { params: { id: string } }) => {
  const diaryId = Number(id);
  const queryClient = new QueryClient();
  const petId = Number(cookies().get("petId")?.value);
  **await queryClient.prefetchQuery({ queryKey: ["diary", { petId, diaryId }], queryFn: () => getDiary({ diaryId }) });**
);

  return (
    <div className={root}>
      <HydrationBoundary state={dehydratedState}>
        <BackHeader title="육아일기" />
        <div className={container}>
          <DiaryDetail petId={petId} diaryId={diaryId} />
        </div>
      </HydrationBoundary>
    </div>
  );
};

export default DiaryDetailPage;

```

```tsx
//페이지 안에 들어가는 클라이언트 컴포넌트: 가져온 petId와 diaryId를 사용해용

"use client"

const DiaryDetail = ({ petId, diaryId }: { petId: number; diaryId: number }) => {
  const [currentPage, setCurrentPage] = useState(0);
  const [isKebabOpen, setIsKebabOpen] = useState(false);
  const [commentValue, setCommentValue] = useState("");
  const { isModalOpen, openModalFunc, closeModalFunc } = useModal();
  const queryClient = useQueryClient();
  const router = useRouter();

  //일기 상세 조회
  **const { data: diary } = useQuery({ queryKey: ["diary", { petId, diaryId }], queryFn: () => getDiary({ diaryId }) });**
```

## 4. 🧐PrefetchQuery 언제 사용하면 좋지?

<img src="https://github.com/QueenCards/ProjectAnalysis/assets/144667455/d8521097-cde6-4148-b74f-ac26d806d11c" width="500">

```ts
import { getComments, getDiary } from "@/app/_api/diary";
import { getMe } from "@/app/_api/users";
import DiaryDetail from "@/app/diary/_components/DiaryDetail";
import { COMMENT_PAGE_SIZE } from "@/app/diary/(diary)/constant";
import { HydrationBoundary, QueryClient, dehydrate } from "@tanstack/react-query";
import { cookies } from "next/headers";

const DiaryDetailPage = async ({ params: { id } }: { params: { id: string } }) => {
  const diaryId = Number(id);
  const queryClient = new QueryClient();
  const petId = Number(cookies().get("petId")?.value);
  await queryClient.prefetchQuery({ queryKey: ["diary", { petId, diaryId }], queryFn: () => getDiary({ diaryId }) });
  await queryClient.prefetchInfiniteQuery({
    queryKey: ["comments", { petId, diaryId }],
    queryFn: ({ pageParam }) => getComments({ diaryId, page: pageParam, size: COMMENT_PAGE_SIZE, petId }),
    initialPageParam: 0,
  });

  //댓글 입력창 프로필 이미지
  await queryClient.prefetchQuery({ queryKey: ["me"], queryFn: () => getMe() });
  const dehydratedState = dehydrate(queryClient);

  return (
    <div className={root}>
      <HydrationBoundary state={dehydratedState}>
        <BackHeader title="육아일기" styleTop="0" />
        <div className={container}>
          <DiaryDetail petId={petId} diaryId={diaryId} />
        </div>
      </HydrationBoundary>
    </div>
  );
};

export default DiaryDetailPage;

```

- **<case.1 > 페이지 안에 A-B-C-D가 차례로 있다고 할 때,  A에 있는 유저가 만약 C에 접근하려면 반드시 B를 거쳐서 A → B → C 로만 접근해야 한다면?**
    
    ⇒ 유저가 B에 접근하는 순간, 혹은 C로 가는 링크컴포넌트에 마우스를 올린 순간!!
         데이터를 미리 가져오면 C에서는 초기 로딩 시간을 단축할 수 있고 유저 경험 향상 可
    
- **<case.2> 유저가 B에 접근하는 순간 C의 데이터를 미리 가져오려고 한다. 그런데 만약 B에 무수히 많은 선택지가 있다면? 혹은 접근 확률이 아주 낮다면?**
    
    ⇒ Prefetch는 확률 게임이라고 할 수 있다…?
    B에서 C-1, C-2, C-3, C-4, C-5… C-16으로 갈 수 있는 선택지가 있다면..? 모든 데이터를 prefetch 할 필요가 없다 (당연,, 그럼 결국 그냥 다 서버에서 받아오는거잖아…~)
    
    ⇒ C는 아주 인기가 없는 컴포넌트여서 접근 확률이 아주아주 낮은데, A에 있는 유저가 만약 C에 접근하려면 반드시 B를 거쳐서 A → B → C 로만 접근해야 한다면..? 굳이 데이터를 캐시에 저장해둘 필요가 있을까? (→ 굳이? 그럴 필요 없다)
    자주 사용하는 데이터를 prefetch하면 좋지만, 인기있는 데이터가 아니라고 해서 꼭 지양해야 하는 것은 아님
    (하고 싶으면 하면 됨,, 일단 SSR이전에 데이터를 받아오기 때문에 UX향상) 
    

## 5. 🧐PrefetchQuery 언제 사용하면 별로지?

- **prefetch 하려는 데이터가 캐러셀 + 무한스크롤 …. 등등 아주 동적인 데이터인 경우**
    
    (cf. 무한스크롤, 페이지네이션을 위한 `prefetchInfiniteQuery` 가 별도로 존재함)

**Comment by Nahyun-Kang** [comment]
**cacheTime :** 메모리에 얼마만큼 있을 것인지, 해당 시간 이후에는 GC( Garbage collector )에 의해 처리가 되며 default 값은 5분입니다.

**staleTime :** 얼마의 시간이 흐른 후에 데이터를 stale( 신선하지 않은 -> 최신 상태가 아닌 ) 취급할 것인지에 해당하는 옵션입니다.

**Comment by Jyophie** [comment]
## React Query의 GC 타임과 Stale Time

**React Query**는 서버 상태 관리 라이브러리로, 데이터 페칭, 캐싱, 동기화 및 서버 상태 업데이트를 간편하게 처리할 수 있게 해줍니다.

### Stale Time

**Stale Time**은 React Query에서 데이터를 '신선한'(fresh) 상태로 간주하는 시간입니다. 즉, 데이터가 서버에서 마지막으로 가져온 이후로 지정된 시간 동안 신선하다고 간주되며, 이 기간 동안에는 재요청을 하지 않습니다.

- **기본 값**: 기본적으로 `0`으로 설정되어 있으며, 이는 데이터가 바로 오래된(stale) 상태로 간주된다는 것을 의미합니다.
- **설정 예제**: `staleTime: 10000` (10초 동안 데이터가 신선한 상태로 간주됨).

```javascript
const { data } = useQuery('todos', fetchTodos, {
  staleTime: 10000, // 10초 동안 데이터가 신선하다고 간주됩니다.
});
```

- **장점**: Stale Time을 적절히 설정하면 불필요한 네트워크 요청을 줄이고, 성능을 최적화할 수 있습니다.
- **사용 예**: 자주 변하지 않는 데이터(예: 사용자 프로필 정보 등)에 유용하게 사용됩니다.

### GC 타임 (Garbage Collection Time)

**GC 타임**은 캐시에 저장된 데이터가 메모리에서 제거될 때까지의 시간을 의미합니다. 이 시간 동안 사용되지 않은 데이터는 자동으로 가비지 컬렉션(GC)되어 메모리에서 해제됩니다.

- **기본 값**: 기본적으로 `5분(300000ms)`으로 설정되어 있습니다.
- **설정 예제**: `cacheTime: 600000` (10분 동안 데이터가 캐시에 유지됨).

```javascript
const { data } = useQuery('todos', fetchTodos, {
  cacheTime: 600000, // 10분 동안 캐시에 데이터가 유지됩니다.
});
```

- **장점**: GC 타임을 적절히 설정하면 메모리 사용을 효율적으로 관리할 수 있습니다.
- **사용 예**: 데이터가 자주 사용되지 않지만, 일정 시간 동안 캐시에 유지되어야 하는 경우에 유용합니다.
