### ISSUE TITLE
[07] 어느 부분에서 SSR을 왜 사용했나요?

### ISSUE THREAD

**Issue by hyeyoonS** [QueenCards/ProjectAnalysis#8]
## ✏ 구술 답변 키워드

- 

## ✏ 서술 답변

-

**Comment by Nahyun-Kang** [comment]
저는 listywave에서 탐색 페이지, 인트로 페이지, 리스트 상세 조회 페이지를 담당했습니다. 이 중, 탐색 페이지에서 SSR을 사용하였습니다. 사용자 인터랙션이 활발하지 않고 정적으로 보여지는 곳이기에 앱 라우터가 기본적으로 지원하는 서버 컴포넌트에 기반하여 만들었습니다. (사실 이 부분은 정적 사이트로 구현했어도 됐을 것 같아 추후 리팩토링 예정에 있습니다.)

**Comment by HaydenDevK** [comment]
기본적으로 대부분의 layout과 page를 SSR로 구현하고, CSR이 필요한 컴포넌트를 분리했습니다.
그 이유는 SSR의 장점인 빠른 초기 로딩 속도를 유저에게 제공하기 위해서 입니다.

**Comment by Jyophie** [comment]
마이펫로그 서비스는 다양한 펫 계정을 등록할 수 있기에 계정 전환이 잦게 일어날 수 있는 서비스입니다. 계정 전환에 따른 초기 렌더링 속도를 빠르게 개선하기 위해 프로젝트 개발 도중에 최상위 페이지를 CSR -> SSR로 변경하고, Hydration 방식을 통해 데이터를 전달하였습니다.

**Comment by hyeyoonS** [comment]
화면을 구성할 때, 유저와 인터렉션하여 동적으로 구성되는 부분은 컴포넌트로 분리하여 클라이언트에서 렌더링을 하고, 그 외 Data Fetch가 필요하지 않은 부분은 서버사이드에서 렌더링합니다.
마이펫의 구독자와 차단 유저 목록을 구성하는 부분에서, 상단에 보여지는 카테고리 레이아웃은 `유저에 따라 변하지 않는 공통된 부분`이기에 서버에서 미리 화면을 구성하여 보여주는` SSR`을 사용하고, 카테고리 아래에 실제 목록을 보여주는 부분은 `유저가 어떤 마이펫을 선택했는지에 따라 달라지는 부분`이기에` CSR`을 사용하였습니다. 

또한 서버사이드 렌더링을 하면 초기 화면이 빠르게 보여지기에, API요청을 통해 목록을 가져오는 동안에는, Data Fetch가 필요하지 않은`상단의 카테고리 바`를 먼저 보여줌으로써 유저 경험을 향상시킬 수 있습니다.

**Comment by olseul** [comment]
저는 처음 관리 페이지로 들어갈 때 보이는 페이지에서 SSR을 사용했습니다. 관리 페이지 중, 나의 프로필 정보를 보여주는 섹션에 SSR을 사용하면 서버에서 이미 렌더링된 페이지를 전송받기 때문에 첫 페이지 로딩 시간을 크게 단축할 수 있습니다. setting페이지는 사용자들이 많이 사용할 주요 페이지이므로, 사용자가 콘텐츠를 기다리는 시간을 줄임으로써 서비스에 대한 만족도를 높일 수 있습니다.

**Comment by wise-Ag** [comment]
일기 목록 페이지와 일기 상세페이지, 반려동물 선택 페이지 등등 대부분의 페이지를 SSR로 구현했습니다.
데이터를 prefetch해서 hydrate시킴으로써 렌더링 속도를 높이고, 사용자와의 인터렉션이 필요한 부분은 클라이언트 컴포넌트로 분리하여 구현했습니다.
